//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for ConfigAnalyzerPolicyRecommendationSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ConfigAnalyzerPolicyRecommendationSingle")]
    public partial class ConfigAnalyzerPolicyRecommendationSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ConfigAnalyzerPolicyRecommendation>
    {
        /// <summary>
        /// Initialize a new ConfigAnalyzerPolicyRecommendationSingle object.
        /// </summary>
        public ConfigAnalyzerPolicyRecommendationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ConfigAnalyzerPolicyRecommendationSingle object.
        /// </summary>
        public ConfigAnalyzerPolicyRecommendationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ConfigAnalyzerPolicyRecommendationSingle object.
        /// </summary>
        public ConfigAnalyzerPolicyRecommendationSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ConfigAnalyzerPolicyRecommendation> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ConfigAnalyzerPolicyRecommendation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Identity
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Identity")]
    [global::Microsoft.OData.Client.EntitySet("ConfigAnalyzerPolicyRecommendation")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ConfigAnalyzerPolicyRecommendation")]
    public partial class ConfigAnalyzerPolicyRecommendation : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Identity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Identity")]
        public virtual string Identity
        {
            get
            {
                return this._Identity;
            }
            set
            {
                this.OnIdentityChanging(value);
                this._Identity = value;
                this.OnIdentityChanged();
                this.OnPropertyChanged("Identity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Identity;
        partial void OnIdentityChanging(string value);
        partial void OnIdentityChanged();
        /// <summary>
        /// There are no comments for Property PolicyGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PolicyGroup")]
        public virtual string PolicyGroup
        {
            get
            {
                return this._PolicyGroup;
            }
            set
            {
                this.OnPolicyGroupChanging(value);
                this._PolicyGroup = value;
                this.OnPolicyGroupChanged();
                this.OnPropertyChanged("PolicyGroup");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PolicyGroup;
        partial void OnPolicyGroupChanging(string value);
        partial void OnPolicyGroupChanged();
        /// <summary>
        /// There are no comments for Property SettingName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SettingName")]
        public virtual string SettingName
        {
            get
            {
                return this._SettingName;
            }
            set
            {
                this.OnSettingNameChanging(value);
                this._SettingName = value;
                this.OnSettingNameChanged();
                this.OnPropertyChanged("SettingName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SettingName;
        partial void OnSettingNameChanging(string value);
        partial void OnSettingNameChanged();
        /// <summary>
        /// There are no comments for Property SettingNameDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SettingNameDescription")]
        public virtual string SettingNameDescription
        {
            get
            {
                return this._SettingNameDescription;
            }
            set
            {
                this.OnSettingNameDescriptionChanging(value);
                this._SettingNameDescription = value;
                this.OnSettingNameDescriptionChanged();
                this.OnPropertyChanged("SettingNameDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SettingNameDescription;
        partial void OnSettingNameDescriptionChanging(string value);
        partial void OnSettingNameDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Policy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Policy")]
        public virtual string Policy
        {
            get
            {
                return this._Policy;
            }
            set
            {
                this.OnPolicyChanging(value);
                this._Policy = value;
                this.OnPolicyChanged();
                this.OnPropertyChanged("Policy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Policy;
        partial void OnPolicyChanging(string value);
        partial void OnPolicyChanged();
        /// <summary>
        /// There are no comments for Property AppliedTo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AppliedTo")]
        public virtual string AppliedTo
        {
            get
            {
                return this._AppliedTo;
            }
            set
            {
                this.OnAppliedToChanging(value);
                this._AppliedTo = value;
                this.OnAppliedToChanged();
                this.OnPropertyChanged("AppliedTo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AppliedTo;
        partial void OnAppliedToChanging(string value);
        partial void OnAppliedToChanged();
        /// <summary>
        /// There are no comments for Property CurrentConfiguration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrentConfiguration")]
        public virtual string CurrentConfiguration
        {
            get
            {
                return this._CurrentConfiguration;
            }
            set
            {
                this.OnCurrentConfigurationChanging(value);
                this._CurrentConfiguration = value;
                this.OnCurrentConfigurationChanged();
                this.OnPropertyChanged("CurrentConfiguration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CurrentConfiguration;
        partial void OnCurrentConfigurationChanging(string value);
        partial void OnCurrentConfigurationChanged();
        /// <summary>
        /// There are no comments for Property LastModified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LastModified")]
        public virtual string LastModified
        {
            get
            {
                return this._LastModified;
            }
            set
            {
                this.OnLastModifiedChanging(value);
                this._LastModified = value;
                this.OnLastModifiedChanged();
                this.OnPropertyChanged("LastModified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LastModified;
        partial void OnLastModifiedChanging(string value);
        partial void OnLastModifiedChanged();
        /// <summary>
        /// There are no comments for Property Recommendation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Recommendation")]
        public virtual string Recommendation
        {
            get
            {
                return this._Recommendation;
            }
            set
            {
                this.OnRecommendationChanging(value);
                this._Recommendation = value;
                this.OnRecommendationChanged();
                this.OnPropertyChanged("Recommendation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Recommendation;
        partial void OnRecommendationChanging(string value);
        partial void OnRecommendationChanged();
        /// <summary>
        /// There are no comments for Property SettingType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SettingType")]
        public virtual string SettingType
        {
            get
            {
                return this._SettingType;
            }
            set
            {
                this.OnSettingTypeChanging(value);
                this._SettingType = value;
                this.OnSettingTypeChanged();
                this.OnPropertyChanged("SettingType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SettingType;
        partial void OnSettingTypeChanging(string value);
        partial void OnSettingTypeChanged();
        /// <summary>
        /// There are no comments for Property Cmdlet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Cmdlet")]
        public virtual string Cmdlet
        {
            get
            {
                return this._Cmdlet;
            }
            set
            {
                this.OnCmdletChanging(value);
                this._Cmdlet = value;
                this.OnCmdletChanged();
                this.OnPropertyChanged("Cmdlet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Cmdlet;
        partial void OnCmdletChanging(string value);
        partial void OnCmdletChanged();
        /// <summary>
        /// There are no comments for Property RuleName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RuleName")]
        public virtual string RuleName
        {
            get
            {
                return this._RuleName;
            }
            set
            {
                this.OnRuleNameChanging(value);
                this._RuleName = value;
                this.OnRuleNameChanged();
                this.OnPropertyChanged("RuleName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RuleName;
        partial void OnRuleNameChanging(string value);
        partial void OnRuleNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
