//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Exchange", "AdminApiClient.For.ExchangeOnline.OData");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("AdminApiClient.For.ExchangeOnline.OData", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Exchange.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Exchange.", clientType.Name);
            }
            if (originalNameAttribute != null)
            {
                return clientType.Namespace + "." + originalNameAttribute.OriginalName;
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for BasicInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BasicInfo")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<BasicInfo> BasicInfo
        {
            get
            {
                if ((this._BasicInfo == null))
                {
                    this._BasicInfo = base.CreateQuery<BasicInfo>("BasicInfo");
                }
                return this._BasicInfo;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<BasicInfo> _BasicInfo;
        /// <summary>
        /// There are no comments for MailboxRecoverableItem in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MailboxRecoverableItem")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<MailboxRecoverableItem> MailboxRecoverableItem
        {
            get
            {
                if ((this._MailboxRecoverableItem == null))
                {
                    this._MailboxRecoverableItem = base.CreateQuery<MailboxRecoverableItem>("MailboxRecoverableItem");
                }
                return this._MailboxRecoverableItem;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<MailboxRecoverableItem> _MailboxRecoverableItem;
        /// <summary>
        /// There are no comments for Mailbox in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Mailbox")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Mailbox> Mailbox
        {
            get
            {
                if ((this._Mailbox == null))
                {
                    this._Mailbox = base.CreateQuery<Mailbox>("Mailbox");
                }
                return this._Mailbox;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<Mailbox> _Mailbox;
        /// <summary>
        /// There are no comments for MailboxAutoReplyConfiguration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MailboxAutoReplyConfiguration")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<MailboxAutoReplyConfiguration> MailboxAutoReplyConfiguration
        {
            get
            {
                if ((this._MailboxAutoReplyConfiguration == null))
                {
                    this._MailboxAutoReplyConfiguration = base.CreateQuery<MailboxAutoReplyConfiguration>("MailboxAutoReplyConfiguration");
                }
                return this._MailboxAutoReplyConfiguration;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<MailboxAutoReplyConfiguration> _MailboxAutoReplyConfiguration;
        /// <summary>
        /// There are no comments for MailboxPlan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MailboxPlan")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<MailboxPlan> MailboxPlan
        {
            get
            {
                if ((this._MailboxPlan == null))
                {
                    this._MailboxPlan = base.CreateQuery<MailboxPlan>("MailboxPlan");
                }
                return this._MailboxPlan;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<MailboxPlan> _MailboxPlan;
        /// <summary>
        /// There are no comments for CasMailbox in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CasMailbox")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<CasMailbox> CasMailbox
        {
            get
            {
                if ((this._CasMailbox == null))
                {
                    this._CasMailbox = base.CreateQuery<CasMailbox>("CasMailbox");
                }
                return this._CasMailbox;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<CasMailbox> _CasMailbox;
        /// <summary>
        /// There are no comments for Recipient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Recipient")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Recipient> Recipient
        {
            get
            {
                if ((this._Recipient == null))
                {
                    this._Recipient = base.CreateQuery<Recipient>("Recipient");
                }
                return this._Recipient;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<Recipient> _Recipient;
        /// <summary>
        /// There are no comments for RetentionPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RetentionPolicy")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<RetentionPolicy> RetentionPolicy
        {
            get
            {
                if ((this._RetentionPolicy == null))
                {
                    this._RetentionPolicy = base.CreateQuery<RetentionPolicy>("RetentionPolicy");
                }
                return this._RetentionPolicy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<RetentionPolicy> _RetentionPolicy;
        /// <summary>
        /// There are no comments for RoleAssignmentPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RoleAssignmentPolicy")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<RoleAssignmentPolicy> RoleAssignmentPolicy
        {
            get
            {
                if ((this._RoleAssignmentPolicy == null))
                {
                    this._RoleAssignmentPolicy = base.CreateQuery<RoleAssignmentPolicy>("RoleAssignmentPolicy");
                }
                return this._RoleAssignmentPolicy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<RoleAssignmentPolicy> _RoleAssignmentPolicy;
        /// <summary>
        /// There are no comments for AddressBookPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AddressBookPolicy")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<AddressBookPolicy> AddressBookPolicy
        {
            get
            {
                if ((this._AddressBookPolicy == null))
                {
                    this._AddressBookPolicy = base.CreateQuery<AddressBookPolicy>("AddressBookPolicy");
                }
                return this._AddressBookPolicy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<AddressBookPolicy> _AddressBookPolicy;
        /// <summary>
        /// There are no comments for SharingPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SharingPolicy")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<SharingPolicy> SharingPolicy
        {
            get
            {
                if ((this._SharingPolicy == null))
                {
                    this._SharingPolicy = base.CreateQuery<SharingPolicy>("SharingPolicy");
                }
                return this._SharingPolicy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<SharingPolicy> _SharingPolicy;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("User")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<User> User
        {
            get
            {
                if ((this._User == null))
                {
                    this._User = base.CreateQuery<User>("User");
                }
                return this._User;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<User> _User;
        /// <summary>
        /// There are no comments for OutboundConnector in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OutboundConnector")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<OutboundConnector> OutboundConnector
        {
            get
            {
                if ((this._OutboundConnector == null))
                {
                    this._OutboundConnector = base.CreateQuery<OutboundConnector>("OutboundConnector");
                }
                return this._OutboundConnector;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<OutboundConnector> _OutboundConnector;
        /// <summary>
        /// There are no comments for InboundConnector in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("InboundConnector")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<InboundConnector> InboundConnector
        {
            get
            {
                if ((this._InboundConnector == null))
                {
                    this._InboundConnector = base.CreateQuery<InboundConnector>("InboundConnector");
                }
                return this._InboundConnector;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<InboundConnector> _InboundConnector;
        /// <summary>
        /// There are no comments for HistoricalSearch in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HistoricalSearch")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<HistoricalSearch> HistoricalSearch
        {
            get
            {
                if ((this._HistoricalSearch == null))
                {
                    this._HistoricalSearch = base.CreateQuery<HistoricalSearch>("HistoricalSearch");
                }
                return this._HistoricalSearch;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<HistoricalSearch> _HistoricalSearch;
        /// <summary>
        /// There are no comments for ReportSchedule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ReportSchedule")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<ReportSchedule> ReportSchedule
        {
            get
            {
                if ((this._ReportSchedule == null))
                {
                    this._ReportSchedule = base.CreateQuery<ReportSchedule>("ReportSchedule");
                }
                return this._ReportSchedule;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<ReportSchedule> _ReportSchedule;
        /// <summary>
        /// There are no comments for CalendarProcessing in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CalendarProcessing")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<CalendarProcessing> CalendarProcessing
        {
            get
            {
                if ((this._CalendarProcessing == null))
                {
                    this._CalendarProcessing = base.CreateQuery<CalendarProcessing>("CalendarProcessing");
                }
                return this._CalendarProcessing;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<CalendarProcessing> _CalendarProcessing;
        /// <summary>
        /// There are no comments for CmdletInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CmdletInfo")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<CmdletInfo> CmdletInfo
        {
            get
            {
                if ((this._CmdletInfo == null))
                {
                    this._CmdletInfo = base.CreateQuery<CmdletInfo>("CmdletInfo");
                }
                return this._CmdletInfo;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<CmdletInfo> _CmdletInfo;
        /// <summary>
        /// There are no comments for Place in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Place")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Place> Place
        {
            get
            {
                if ((this._Place == null))
                {
                    this._Place = base.CreateQuery<Place>("Place");
                }
                return this._Place;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<Place> _Place;
        /// <summary>
        /// There are no comments for RoleDefinitions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RoleDefinitions")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<RoleDefinitions> RoleDefinitions
        {
            get
            {
                if ((this._RoleDefinitions == null))
                {
                    this._RoleDefinitions = base.CreateQuery<RoleDefinitions>("RoleDefinitions");
                }
                return this._RoleDefinitions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<RoleDefinitions> _RoleDefinitions;
        /// <summary>
        /// There are no comments for ExchangeRoleGroupMember in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ExchangeRoleGroupMember")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<ExchangeRoleGroupMember> ExchangeRoleGroupMember
        {
            get
            {
                if ((this._ExchangeRoleGroupMember == null))
                {
                    this._ExchangeRoleGroupMember = base.CreateQuery<ExchangeRoleGroupMember>("ExchangeRoleGroupMember");
                }
                return this._ExchangeRoleGroupMember;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<ExchangeRoleGroupMember> _ExchangeRoleGroupMember;
        /// <summary>
        /// There are no comments for ExchangeRoleGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ExchangeRoleGroup")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<ExchangeRoleGroup> ExchangeRoleGroup
        {
            get
            {
                if ((this._ExchangeRoleGroup == null))
                {
                    this._ExchangeRoleGroup = base.CreateQuery<ExchangeRoleGroup>("ExchangeRoleGroup");
                }
                return this._ExchangeRoleGroup;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<ExchangeRoleGroup> _ExchangeRoleGroup;
        /// <summary>
        /// There are no comments for ExchangeManagementScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ExchangeManagementScope")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<ExchangeManagementScope> ExchangeManagementScope
        {
            get
            {
                if ((this._ExchangeManagementScope == null))
                {
                    this._ExchangeManagementScope = base.CreateQuery<ExchangeManagementScope>("ExchangeManagementScope");
                }
                return this._ExchangeManagementScope;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<ExchangeManagementScope> _ExchangeManagementScope;
        /// <summary>
        /// There are no comments for RoleAssignments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RoleAssignments")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<RoleAssignments> RoleAssignments
        {
            get
            {
                if ((this._RoleAssignments == null))
                {
                    this._RoleAssignments = base.CreateQuery<RoleAssignments>("RoleAssignments");
                }
                return this._RoleAssignments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<RoleAssignments> _RoleAssignments;
        /// <summary>
        /// There are no comments for SecurityPrincipal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityPrincipal")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<SecurityPrincipal> SecurityPrincipal
        {
            get
            {
                if ((this._SecurityPrincipal == null))
                {
                    this._SecurityPrincipal = base.CreateQuery<SecurityPrincipal>("SecurityPrincipal");
                }
                return this._SecurityPrincipal;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<SecurityPrincipal> _SecurityPrincipal;
        /// <summary>
        /// There are no comments for HostedContentFilterPolicyPresentation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HostedContentFilterPolicyPresentation")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<HostedContentFilterPolicyPresentation> HostedContentFilterPolicyPresentation
        {
            get
            {
                if ((this._HostedContentFilterPolicyPresentation == null))
                {
                    this._HostedContentFilterPolicyPresentation = base.CreateQuery<HostedContentFilterPolicyPresentation>("HostedContentFilterPolicyPresentation");
                }
                return this._HostedContentFilterPolicyPresentation;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<HostedContentFilterPolicyPresentation> _HostedContentFilterPolicyPresentation;
        /// <summary>
        /// There are no comments for AntiPhishPolicyPresentation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AntiPhishPolicyPresentation")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<AntiPhishPolicyPresentation> AntiPhishPolicyPresentation
        {
            get
            {
                if ((this._AntiPhishPolicyPresentation == null))
                {
                    this._AntiPhishPolicyPresentation = base.CreateQuery<AntiPhishPolicyPresentation>("AntiPhishPolicyPresentation");
                }
                return this._AntiPhishPolicyPresentation;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<AntiPhishPolicyPresentation> _AntiPhishPolicyPresentation;
        /// <summary>
        /// There are no comments for MalwareFilterPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MalwareFilterPolicy")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<MalwareFilterPolicy> MalwareFilterPolicy
        {
            get
            {
                if ((this._MalwareFilterPolicy == null))
                {
                    this._MalwareFilterPolicy = base.CreateQuery<MalwareFilterPolicy>("MalwareFilterPolicy");
                }
                return this._MalwareFilterPolicy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<MalwareFilterPolicy> _MalwareFilterPolicy;
        /// <summary>
        /// There are no comments for SafeAttachmentPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SafeAttachmentPolicy")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<SafeAttachmentPolicy> SafeAttachmentPolicy
        {
            get
            {
                if ((this._SafeAttachmentPolicy == null))
                {
                    this._SafeAttachmentPolicy = base.CreateQuery<SafeAttachmentPolicy>("SafeAttachmentPolicy");
                }
                return this._SafeAttachmentPolicy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<SafeAttachmentPolicy> _SafeAttachmentPolicy;
        /// <summary>
        /// There are no comments for SafeLinksPolicyPresentation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SafeLinksPolicyPresentation")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<SafeLinksPolicyPresentation> SafeLinksPolicyPresentation
        {
            get
            {
                if ((this._SafeLinksPolicyPresentation == null))
                {
                    this._SafeLinksPolicyPresentation = base.CreateQuery<SafeLinksPolicyPresentation>("SafeLinksPolicyPresentation");
                }
                return this._SafeLinksPolicyPresentation;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<SafeLinksPolicyPresentation> _SafeLinksPolicyPresentation;
        /// <summary>
        /// There are no comments for HostedContentFilterRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HostedContentFilterRule")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<HostedContentFilterRule> HostedContentFilterRule
        {
            get
            {
                if ((this._HostedContentFilterRule == null))
                {
                    this._HostedContentFilterRule = base.CreateQuery<HostedContentFilterRule>("HostedContentFilterRule");
                }
                return this._HostedContentFilterRule;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<HostedContentFilterRule> _HostedContentFilterRule;
        /// <summary>
        /// There are no comments for AntiPhishRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AntiPhishRule")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<AntiPhishRule> AntiPhishRule
        {
            get
            {
                if ((this._AntiPhishRule == null))
                {
                    this._AntiPhishRule = base.CreateQuery<AntiPhishRule>("AntiPhishRule");
                }
                return this._AntiPhishRule;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<AntiPhishRule> _AntiPhishRule;
        /// <summary>
        /// There are no comments for MalwareFilterRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MalwareFilterRule")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<MalwareFilterRule> MalwareFilterRule
        {
            get
            {
                if ((this._MalwareFilterRule == null))
                {
                    this._MalwareFilterRule = base.CreateQuery<MalwareFilterRule>("MalwareFilterRule");
                }
                return this._MalwareFilterRule;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<MalwareFilterRule> _MalwareFilterRule;
        /// <summary>
        /// There are no comments for SafeAttachmentRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SafeAttachmentRule")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<SafeAttachmentRule> SafeAttachmentRule
        {
            get
            {
                if ((this._SafeAttachmentRule == null))
                {
                    this._SafeAttachmentRule = base.CreateQuery<SafeAttachmentRule>("SafeAttachmentRule");
                }
                return this._SafeAttachmentRule;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<SafeAttachmentRule> _SafeAttachmentRule;
        /// <summary>
        /// There are no comments for SafeLinksRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SafeLinksRule")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<SafeLinksRule> SafeLinksRule
        {
            get
            {
                if ((this._SafeLinksRule == null))
                {
                    this._SafeLinksRule = base.CreateQuery<SafeLinksRule>("SafeLinksRule");
                }
                return this._SafeLinksRule;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<SafeLinksRule> _SafeLinksRule;
        /// <summary>
        /// There are no comments for ConfigAnalyzerPolicyRecommendation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ConfigAnalyzerPolicyRecommendation")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<ConfigAnalyzerPolicyRecommendation> ConfigAnalyzerPolicyRecommendation
        {
            get
            {
                if ((this._ConfigAnalyzerPolicyRecommendation == null))
                {
                    this._ConfigAnalyzerPolicyRecommendation = base.CreateQuery<ConfigAnalyzerPolicyRecommendation>("ConfigAnalyzerPolicyRecommendation");
                }
                return this._ConfigAnalyzerPolicyRecommendation;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<ConfigAnalyzerPolicyRecommendation> _ConfigAnalyzerPolicyRecommendation;
        /// <summary>
        /// There are no comments for AtpPolicyForO365Presentation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AtpPolicyForO365Presentation")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<AtpPolicyForO365Presentation> AtpPolicyForO365Presentation
        {
            get
            {
                if ((this._AtpPolicyForO365Presentation == null))
                {
                    this._AtpPolicyForO365Presentation = base.CreateQuery<AtpPolicyForO365Presentation>("AtpPolicyForO365Presentation");
                }
                return this._AtpPolicyForO365Presentation;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<AtpPolicyForO365Presentation> _AtpPolicyForO365Presentation;
        /// <summary>
        /// There are no comments for GraphConnectorGroupMember in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("GraphConnectorGroupMember")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<GraphConnectorGroupMember> GraphConnectorGroupMember
        {
            get
            {
                if ((this._GraphConnectorGroupMember == null))
                {
                    this._GraphConnectorGroupMember = base.CreateQuery<GraphConnectorGroupMember>("GraphConnectorGroupMember");
                }
                return this._GraphConnectorGroupMember;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<GraphConnectorGroupMember> _GraphConnectorGroupMember;
        /// <summary>
        /// There are no comments for GraphConnectorGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("GraphConnectorGroup")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<GraphConnectorGroup> GraphConnectorGroup
        {
            get
            {
                if ((this._GraphConnectorGroup == null))
                {
                    this._GraphConnectorGroup = base.CreateQuery<GraphConnectorGroup>("GraphConnectorGroup");
                }
                return this._GraphConnectorGroup;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<GraphConnectorGroup> _GraphConnectorGroup;
        /// <summary>
        /// There are no comments for EligibleDistributionGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EligibleDistributionGroup")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<EligibleDistributionGroup> EligibleDistributionGroup
        {
            get
            {
                if ((this._EligibleDistributionGroup == null))
                {
                    this._EligibleDistributionGroup = base.CreateQuery<EligibleDistributionGroup>("EligibleDistributionGroup");
                }
                return this._EligibleDistributionGroup;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<EligibleDistributionGroup> _EligibleDistributionGroup;
        /// <summary>
        /// There are no comments for DynamicDistributionGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicDistributionGroup")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<DynamicDistributionGroup> DynamicDistributionGroup
        {
            get
            {
                if ((this._DynamicDistributionGroup == null))
                {
                    this._DynamicDistributionGroup = base.CreateQuery<DynamicDistributionGroup>("DynamicDistributionGroup");
                }
                return this._DynamicDistributionGroup;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<DynamicDistributionGroup> _DynamicDistributionGroup;
        /// <summary>
        /// There are no comments for ActiveSyncOrganizationSettings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ActiveSyncOrganizationSettings")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<ActiveSyncOrganizationSettings> ActiveSyncOrganizationSettings
        {
            get
            {
                if ((this._ActiveSyncOrganizationSettings == null))
                {
                    this._ActiveSyncOrganizationSettings = base.CreateQuery<ActiveSyncOrganizationSettings>("ActiveSyncOrganizationSettings");
                }
                return this._ActiveSyncOrganizationSettings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<ActiveSyncOrganizationSettings> _ActiveSyncOrganizationSettings;
        /// <summary>
        /// There are no comments for UnifiedGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UnifiedGroup")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<UnifiedGroup> UnifiedGroup
        {
            get
            {
                if ((this._UnifiedGroup == null))
                {
                    this._UnifiedGroup = base.CreateQuery<UnifiedGroup>("UnifiedGroup");
                }
                return this._UnifiedGroup;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<UnifiedGroup> _UnifiedGroup;
        /// <summary>
        /// There are no comments for MobileDeviceMailboxPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MobileDeviceMailboxPolicy")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<MobileDeviceMailboxPolicy> MobileDeviceMailboxPolicy
        {
            get
            {
                if ((this._MobileDeviceMailboxPolicy == null))
                {
                    this._MobileDeviceMailboxPolicy = base.CreateQuery<MobileDeviceMailboxPolicy>("MobileDeviceMailboxPolicy");
                }
                return this._MobileDeviceMailboxPolicy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<MobileDeviceMailboxPolicy> _MobileDeviceMailboxPolicy;
        /// <summary>
        /// There are no comments for ActiveSyncDeviceAccessRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ActiveSyncDeviceAccessRule")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<ActiveSyncDeviceAccessRule> ActiveSyncDeviceAccessRule
        {
            get
            {
                if ((this._ActiveSyncDeviceAccessRule == null))
                {
                    this._ActiveSyncDeviceAccessRule = base.CreateQuery<ActiveSyncDeviceAccessRule>("ActiveSyncDeviceAccessRule");
                }
                return this._ActiveSyncDeviceAccessRule;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<ActiveSyncDeviceAccessRule> _ActiveSyncDeviceAccessRule;
        /// <summary>
        /// There are no comments for ActiveSyncDeviceClass in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ActiveSyncDeviceClass")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<ActiveSyncDeviceClass> ActiveSyncDeviceClass
        {
            get
            {
                if ((this._ActiveSyncDeviceClass == null))
                {
                    this._ActiveSyncDeviceClass = base.CreateQuery<ActiveSyncDeviceClass>("ActiveSyncDeviceClass");
                }
                return this._ActiveSyncDeviceClass;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<ActiveSyncDeviceClass> _ActiveSyncDeviceClass;
        /// <summary>
        /// There are no comments for DirectMobileDevice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DirectMobileDevice")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<DirectMobileDevice> DirectMobileDevice
        {
            get
            {
                if ((this._DirectMobileDevice == null))
                {
                    this._DirectMobileDevice = base.CreateQuery<DirectMobileDevice>("DirectMobileDevice");
                }
                return this._DirectMobileDevice;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<DirectMobileDevice> _DirectMobileDevice;
        /// <summary>
        /// There are no comments for Divergence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Divergence")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Divergence> Divergence
        {
            get
            {
                if ((this._Divergence == null))
                {
                    this._Divergence = base.CreateQuery<Divergence>("Divergence");
                }
                return this._Divergence;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<Divergence> _Divergence;
        /// <summary>
        /// There are no comments for BasicInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToBasicInfo(BasicInfo basicInfo)
        {
            base.AddObject("BasicInfo", basicInfo);
        }
        /// <summary>
        /// There are no comments for MailboxRecoverableItem in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMailboxRecoverableItem(MailboxRecoverableItem mailboxRecoverableItem)
        {
            base.AddObject("MailboxRecoverableItem", mailboxRecoverableItem);
        }
        /// <summary>
        /// There are no comments for Mailbox in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMailbox(Mailbox mailbox)
        {
            base.AddObject("Mailbox", mailbox);
        }
        /// <summary>
        /// There are no comments for MailboxAutoReplyConfiguration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMailboxAutoReplyConfiguration(MailboxAutoReplyConfiguration mailboxAutoReplyConfiguration)
        {
            base.AddObject("MailboxAutoReplyConfiguration", mailboxAutoReplyConfiguration);
        }
        /// <summary>
        /// There are no comments for MailboxPlan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMailboxPlan(MailboxPlan mailboxPlan)
        {
            base.AddObject("MailboxPlan", mailboxPlan);
        }
        /// <summary>
        /// There are no comments for CasMailbox in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCasMailbox(CasMailbox casMailbox)
        {
            base.AddObject("CasMailbox", casMailbox);
        }
        /// <summary>
        /// There are no comments for Recipient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToRecipient(Recipient recipient)
        {
            base.AddObject("Recipient", recipient);
        }
        /// <summary>
        /// There are no comments for RetentionPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToRetentionPolicy(RetentionPolicy retentionPolicy)
        {
            base.AddObject("RetentionPolicy", retentionPolicy);
        }
        /// <summary>
        /// There are no comments for RoleAssignmentPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToRoleAssignmentPolicy(RoleAssignmentPolicy roleAssignmentPolicy)
        {
            base.AddObject("RoleAssignmentPolicy", roleAssignmentPolicy);
        }
        /// <summary>
        /// There are no comments for AddressBookPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToAddressBookPolicy(AddressBookPolicy addressBookPolicy)
        {
            base.AddObject("AddressBookPolicy", addressBookPolicy);
        }
        /// <summary>
        /// There are no comments for SharingPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToSharingPolicy(SharingPolicy sharingPolicy)
        {
            base.AddObject("SharingPolicy", sharingPolicy);
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
        /// <summary>
        /// There are no comments for OutboundConnector in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToOutboundConnector(OutboundConnector outboundConnector)
        {
            base.AddObject("OutboundConnector", outboundConnector);
        }
        /// <summary>
        /// There are no comments for InboundConnector in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToInboundConnector(InboundConnector inboundConnector)
        {
            base.AddObject("InboundConnector", inboundConnector);
        }
        /// <summary>
        /// There are no comments for HistoricalSearch in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToHistoricalSearch(HistoricalSearch historicalSearch)
        {
            base.AddObject("HistoricalSearch", historicalSearch);
        }
        /// <summary>
        /// There are no comments for ReportSchedule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToReportSchedule(ReportSchedule reportSchedule)
        {
            base.AddObject("ReportSchedule", reportSchedule);
        }
        /// <summary>
        /// There are no comments for CalendarProcessing in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCalendarProcessing(CalendarProcessing calendarProcessing)
        {
            base.AddObject("CalendarProcessing", calendarProcessing);
        }
        /// <summary>
        /// There are no comments for CmdletInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCmdletInfo(CmdletInfo cmdletInfo)
        {
            base.AddObject("CmdletInfo", cmdletInfo);
        }
        /// <summary>
        /// There are no comments for Place in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToPlace(Place place)
        {
            base.AddObject("Place", place);
        }
        /// <summary>
        /// There are no comments for RoleDefinitions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToRoleDefinitions(RoleDefinitions roleDefinitions)
        {
            base.AddObject("RoleDefinitions", roleDefinitions);
        }
        /// <summary>
        /// There are no comments for ExchangeRoleGroupMember in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToExchangeRoleGroupMember(ExchangeRoleGroupMember exchangeRoleGroupMember)
        {
            base.AddObject("ExchangeRoleGroupMember", exchangeRoleGroupMember);
        }
        /// <summary>
        /// There are no comments for ExchangeRoleGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToExchangeRoleGroup(ExchangeRoleGroup exchangeRoleGroup)
        {
            base.AddObject("ExchangeRoleGroup", exchangeRoleGroup);
        }
        /// <summary>
        /// There are no comments for ExchangeManagementScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToExchangeManagementScope(ExchangeManagementScope exchangeManagementScope)
        {
            base.AddObject("ExchangeManagementScope", exchangeManagementScope);
        }
        /// <summary>
        /// There are no comments for RoleAssignments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToRoleAssignments(RoleAssignments roleAssignments)
        {
            base.AddObject("RoleAssignments", roleAssignments);
        }
        /// <summary>
        /// There are no comments for SecurityPrincipal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToSecurityPrincipal(SecurityPrincipal securityPrincipal)
        {
            base.AddObject("SecurityPrincipal", securityPrincipal);
        }
        /// <summary>
        /// There are no comments for HostedContentFilterPolicyPresentation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToHostedContentFilterPolicyPresentation(HostedContentFilterPolicyPresentation hostedContentFilterPolicyPresentation)
        {
            base.AddObject("HostedContentFilterPolicyPresentation", hostedContentFilterPolicyPresentation);
        }
        /// <summary>
        /// There are no comments for AntiPhishPolicyPresentation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToAntiPhishPolicyPresentation(AntiPhishPolicyPresentation antiPhishPolicyPresentation)
        {
            base.AddObject("AntiPhishPolicyPresentation", antiPhishPolicyPresentation);
        }
        /// <summary>
        /// There are no comments for MalwareFilterPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMalwareFilterPolicy(MalwareFilterPolicy malwareFilterPolicy)
        {
            base.AddObject("MalwareFilterPolicy", malwareFilterPolicy);
        }
        /// <summary>
        /// There are no comments for SafeAttachmentPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToSafeAttachmentPolicy(SafeAttachmentPolicy safeAttachmentPolicy)
        {
            base.AddObject("SafeAttachmentPolicy", safeAttachmentPolicy);
        }
        /// <summary>
        /// There are no comments for SafeLinksPolicyPresentation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToSafeLinksPolicyPresentation(SafeLinksPolicyPresentation safeLinksPolicyPresentation)
        {
            base.AddObject("SafeLinksPolicyPresentation", safeLinksPolicyPresentation);
        }
        /// <summary>
        /// There are no comments for HostedContentFilterRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToHostedContentFilterRule(HostedContentFilterRule hostedContentFilterRule)
        {
            base.AddObject("HostedContentFilterRule", hostedContentFilterRule);
        }
        /// <summary>
        /// There are no comments for AntiPhishRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToAntiPhishRule(AntiPhishRule antiPhishRule)
        {
            base.AddObject("AntiPhishRule", antiPhishRule);
        }
        /// <summary>
        /// There are no comments for MalwareFilterRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMalwareFilterRule(MalwareFilterRule malwareFilterRule)
        {
            base.AddObject("MalwareFilterRule", malwareFilterRule);
        }
        /// <summary>
        /// There are no comments for SafeAttachmentRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToSafeAttachmentRule(SafeAttachmentRule safeAttachmentRule)
        {
            base.AddObject("SafeAttachmentRule", safeAttachmentRule);
        }
        /// <summary>
        /// There are no comments for SafeLinksRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToSafeLinksRule(SafeLinksRule safeLinksRule)
        {
            base.AddObject("SafeLinksRule", safeLinksRule);
        }
        /// <summary>
        /// There are no comments for ConfigAnalyzerPolicyRecommendation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToConfigAnalyzerPolicyRecommendation(ConfigAnalyzerPolicyRecommendation configAnalyzerPolicyRecommendation)
        {
            base.AddObject("ConfigAnalyzerPolicyRecommendation", configAnalyzerPolicyRecommendation);
        }
        /// <summary>
        /// There are no comments for AtpPolicyForO365Presentation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToAtpPolicyForO365Presentation(AtpPolicyForO365Presentation atpPolicyForO365Presentation)
        {
            base.AddObject("AtpPolicyForO365Presentation", atpPolicyForO365Presentation);
        }
        /// <summary>
        /// There are no comments for GraphConnectorGroupMember in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToGraphConnectorGroupMember(GraphConnectorGroupMember graphConnectorGroupMember)
        {
            base.AddObject("GraphConnectorGroupMember", graphConnectorGroupMember);
        }
        /// <summary>
        /// There are no comments for GraphConnectorGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToGraphConnectorGroup(GraphConnectorGroup graphConnectorGroup)
        {
            base.AddObject("GraphConnectorGroup", graphConnectorGroup);
        }
        /// <summary>
        /// There are no comments for EligibleDistributionGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToEligibleDistributionGroup(EligibleDistributionGroup eligibleDistributionGroup)
        {
            base.AddObject("EligibleDistributionGroup", eligibleDistributionGroup);
        }
        /// <summary>
        /// There are no comments for DynamicDistributionGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToDynamicDistributionGroup(DynamicDistributionGroup dynamicDistributionGroup)
        {
            base.AddObject("DynamicDistributionGroup", dynamicDistributionGroup);
        }
        /// <summary>
        /// There are no comments for ActiveSyncOrganizationSettings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToActiveSyncOrganizationSettings(ActiveSyncOrganizationSettings activeSyncOrganizationSettings)
        {
            base.AddObject("ActiveSyncOrganizationSettings", activeSyncOrganizationSettings);
        }
        /// <summary>
        /// There are no comments for UnifiedGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToUnifiedGroup(UnifiedGroup unifiedGroup)
        {
            base.AddObject("UnifiedGroup", unifiedGroup);
        }
        /// <summary>
        /// There are no comments for MobileDeviceMailboxPolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMobileDeviceMailboxPolicy(MobileDeviceMailboxPolicy mobileDeviceMailboxPolicy)
        {
            base.AddObject("MobileDeviceMailboxPolicy", mobileDeviceMailboxPolicy);
        }
        /// <summary>
        /// There are no comments for ActiveSyncDeviceAccessRule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToActiveSyncDeviceAccessRule(ActiveSyncDeviceAccessRule activeSyncDeviceAccessRule)
        {
            base.AddObject("ActiveSyncDeviceAccessRule", activeSyncDeviceAccessRule);
        }
        /// <summary>
        /// There are no comments for ActiveSyncDeviceClass in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToActiveSyncDeviceClass(ActiveSyncDeviceClass activeSyncDeviceClass)
        {
            base.AddObject("ActiveSyncDeviceClass", activeSyncDeviceClass);
        }
        /// <summary>
        /// There are no comments for DirectMobileDevice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToDirectMobileDevice(DirectMobileDevice directMobileDevice)
        {
            base.AddObject("DirectMobileDevice", directMobileDevice);
        }
        /// <summary>
        /// There are no comments for Divergence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToDivergence(Divergence divergence)
        {
            base.AddObject("Divergence", divergence);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"ExchangeOnlineAdminApiCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
        /// <summary>
        /// There are no comments for GetMobileDeviceStatisticsByIdentity in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetMobileDeviceStatisticsByIdentity")]
        public virtual global::Microsoft.OData.Client.DataServiceQuerySingle<global::AdminApiClient.For.ExchangeOnline.OData.MobileDeviceStatistics> GetMobileDeviceStatisticsByIdentity(string Identity)
        {
            return this.CreateFunctionQuerySingle<global::AdminApiClient.For.ExchangeOnline.OData.MobileDeviceStatistics>("", "GetMobileDeviceStatisticsByIdentity", false, new global::Microsoft.OData.Client.UriOperationParameter("Identity", Identity));
        }
        /// <summary>
        /// There are no comments for SearchMessageTrace in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("SearchMessageTrace")]
        public virtual global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.MessageTrace> SearchMessageTrace(global::AdminApiClient.For.ExchangeOnline.OData.GenericHashTable QueryTable)
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.MessageTrace>(this, this.BaseUri.OriginalString.Trim('/') + "/SearchMessageTrace", new global::Microsoft.OData.Client.BodyOperationParameter("QueryTable", QueryTable));
        }
        /// <summary>
        /// There are no comments for SearchMessageTraceDetail in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("SearchMessageTraceDetail")]
        public virtual global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.MessageTraceDetail> SearchMessageTraceDetail(global::AdminApiClient.For.ExchangeOnline.OData.GenericHashTable QueryTable)
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.MessageTraceDetail>(this, this.BaseUri.OriginalString.Trim('/') + "/SearchMessageTraceDetail", new global::Microsoft.OData.Client.BodyOperationParameter("QueryTable", QueryTable));
        }
        /// <summary>
        /// There are no comments for GetMailDetailTransportRuleReport in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetMailDetailTransportRuleReport")]
        public virtual global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.MailDetailTransportRuleReport> GetMailDetailTransportRuleReport(global::AdminApiClient.For.ExchangeOnline.OData.GenericHashTable QueryTable)
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.MailDetailTransportRuleReport>(this, this.BaseUri.OriginalString.Trim('/') + "/GetMailDetailTransportRuleReport", new global::Microsoft.OData.Client.BodyOperationParameter("QueryTable", QueryTable));
        }
        /// <summary>
        /// There are no comments for GetMailTrafficPolicyReport in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetMailTrafficPolicyReport")]
        public virtual global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.MailTrafficPolicyReport> GetMailTrafficPolicyReport(global::AdminApiClient.For.ExchangeOnline.OData.GenericHashTable QueryTable)
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.MailTrafficPolicyReport>(this, this.BaseUri.OriginalString.Trim('/') + "/GetMailTrafficPolicyReport", new global::Microsoft.OData.Client.BodyOperationParameter("QueryTable", QueryTable));
        }
        /// <summary>
        /// There are no comments for GetMailDetailDlpPolicyReport in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetMailDetailDlpPolicyReport")]
        public virtual global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.MailDetailDlpPolicyReport> GetMailDetailDlpPolicyReport(global::AdminApiClient.For.ExchangeOnline.OData.GenericHashTable QueryTable)
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.MailDetailDlpPolicyReport>(this, this.BaseUri.OriginalString.Trim('/') + "/GetMailDetailDlpPolicyReport", new global::Microsoft.OData.Client.BodyOperationParameter("QueryTable", QueryTable));
        }
        /// <summary>
        /// There are no comments for Initialize in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("Initialize")]
        public virtual global::Microsoft.OData.Client.DataServiceActionQuerySingle<string> Initialize()
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<string>(this, this.BaseUri.OriginalString.Trim('/') + "/Initialize");
        }
        /// <summary>
        /// There are no comments for InvokeCommand in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("InvokeCommand")]
        public virtual global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.GenericHashTable> InvokeCommand(global::AdminApiClient.For.ExchangeOnline.OData.CmdletInvokeInputType CmdletInput)
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery<global::AdminApiClient.For.ExchangeOnline.OData.GenericHashTable>(this, this.BaseUri.OriginalString.Trim('/') + "/InvokeCommand", new global::Microsoft.OData.Client.BodyOperationParameter("CmdletInput", CmdletInput));
        }
    }
}
