//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for DynamicDistributionGroupSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicDistributionGroupSingle")]
    public partial class DynamicDistributionGroupSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<DynamicDistributionGroup>
    {
        /// <summary>
        /// Initialize a new DynamicDistributionGroupSingle object.
        /// </summary>
        public DynamicDistributionGroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DynamicDistributionGroupSingle object.
        /// </summary>
        public DynamicDistributionGroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DynamicDistributionGroupSingle object.
        /// </summary>
        public DynamicDistributionGroupSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<DynamicDistributionGroup> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for DynamicDistributionGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Guid
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Guid")]
    [global::Microsoft.OData.Client.EntitySet("DynamicDistributionGroup")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicDistributionGroup")]
    public partial class DynamicDistributionGroup : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Identity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Identity")]
        public virtual string Identity
        {
            get
            {
                return this._Identity;
            }
            set
            {
                this.OnIdentityChanging(value);
                this._Identity = value;
                this.OnIdentityChanged();
                this.OnPropertyChanged("Identity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Identity;
        partial void OnIdentityChanging(string value);
        partial void OnIdentityChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public virtual string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Guid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Guid")]
        public virtual string Guid
        {
            get
            {
                return this._Guid;
            }
            set
            {
                this.OnGuidChanging(value);
                this._Guid = value;
                this.OnGuidChanged();
                this.OnPropertyChanged("Guid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Guid;
        partial void OnGuidChanging(string value);
        partial void OnGuidChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Notes")]
        public virtual string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property DisplayName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DisplayName")]
        public virtual string DisplayName
        {
            get
            {
                return this._DisplayName;
            }
            set
            {
                this.OnDisplayNameChanging(value);
                this._DisplayName = value;
                this.OnDisplayNameChanged();
                this.OnPropertyChanged("DisplayName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DisplayName;
        partial void OnDisplayNameChanging(string value);
        partial void OnDisplayNameChanged();
        /// <summary>
        /// There are no comments for Property Alias in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Alias")]
        public virtual string Alias
        {
            get
            {
                return this._Alias;
            }
            set
            {
                this.OnAliasChanging(value);
                this._Alias = value;
                this.OnAliasChanged();
                this.OnPropertyChanged("Alias");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Alias;
        partial void OnAliasChanging(string value);
        partial void OnAliasChanged();
        /// <summary>
        /// There are no comments for Property DistinguishedName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DistinguishedName")]
        public virtual string DistinguishedName
        {
            get
            {
                return this._DistinguishedName;
            }
            set
            {
                this.OnDistinguishedNameChanging(value);
                this._DistinguishedName = value;
                this.OnDistinguishedNameChanged();
                this.OnPropertyChanged("DistinguishedName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DistinguishedName;
        partial void OnDistinguishedNameChanging(string value);
        partial void OnDistinguishedNameChanged();
        /// <summary>
        /// There are no comments for Property WindowsLiveID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WindowsLiveID")]
        public virtual string WindowsLiveID
        {
            get
            {
                return this._WindowsLiveID;
            }
            set
            {
                this.OnWindowsLiveIDChanging(value);
                this._WindowsLiveID = value;
                this.OnWindowsLiveIDChanged();
                this.OnPropertyChanged("WindowsLiveID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _WindowsLiveID;
        partial void OnWindowsLiveIDChanging(string value);
        partial void OnWindowsLiveIDChanged();
        /// <summary>
        /// There are no comments for Property PrimarySmtpAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PrimarySmtpAddress")]
        public virtual string PrimarySmtpAddress
        {
            get
            {
                return this._PrimarySmtpAddress;
            }
            set
            {
                this.OnPrimarySmtpAddressChanging(value);
                this._PrimarySmtpAddress = value;
                this.OnPrimarySmtpAddressChanged();
                this.OnPropertyChanged("PrimarySmtpAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PrimarySmtpAddress;
        partial void OnPrimarySmtpAddressChanging(string value);
        partial void OnPrimarySmtpAddressChanged();
        /// <summary>
        /// There are no comments for Property IncludedRecipients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IncludedRecipients")]
        public virtual global::System.Nullable<int> IncludedRecipients
        {
            get
            {
                return this._IncludedRecipients;
            }
            set
            {
                this.OnIncludedRecipientsChanging(value);
                this._IncludedRecipients = value;
                this.OnIncludedRecipientsChanged();
                this.OnPropertyChanged("IncludedRecipients");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _IncludedRecipients;
        partial void OnIncludedRecipientsChanging(global::System.Nullable<int> value);
        partial void OnIncludedRecipientsChanged();
        /// <summary>
        /// There are no comments for Property LdapRecipientFilter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LdapRecipientFilter")]
        public virtual string LdapRecipientFilter
        {
            get
            {
                return this._LdapRecipientFilter;
            }
            set
            {
                this.OnLdapRecipientFilterChanging(value);
                this._LdapRecipientFilter = value;
                this.OnLdapRecipientFilterChanged();
                this.OnPropertyChanged("LdapRecipientFilter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LdapRecipientFilter;
        partial void OnLdapRecipientFilterChanging(string value);
        partial void OnLdapRecipientFilterChanged();
        /// <summary>
        /// There are no comments for Property RecipientFilterType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RecipientFilterType")]
        public virtual string RecipientFilterType
        {
            get
            {
                return this._RecipientFilterType;
            }
            set
            {
                this.OnRecipientFilterTypeChanging(value);
                this._RecipientFilterType = value;
                this.OnRecipientFilterTypeChanged();
                this.OnPropertyChanged("RecipientFilterType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RecipientFilterType;
        partial void OnRecipientFilterTypeChanging(string value);
        partial void OnRecipientFilterTypeChanged();
        /// <summary>
        /// There are no comments for Property RecipientFilter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RecipientFilter")]
        public virtual string RecipientFilter
        {
            get
            {
                return this._RecipientFilter;
            }
            set
            {
                this.OnRecipientFilterChanging(value);
                this._RecipientFilter = value;
                this.OnRecipientFilterChanged();
                this.OnPropertyChanged("RecipientFilter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RecipientFilter;
        partial void OnRecipientFilterChanging(string value);
        partial void OnRecipientFilterChanged();
        /// <summary>
        /// There are no comments for Property ManagedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ManagedBy")]
        public virtual string ManagedBy
        {
            get
            {
                return this._ManagedBy;
            }
            set
            {
                this.OnManagedByChanging(value);
                this._ManagedBy = value;
                this.OnManagedByChanged();
                this.OnPropertyChanged("ManagedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ManagedBy;
        partial void OnManagedByChanging(string value);
        partial void OnManagedByChanged();
        /// <summary>
        /// There are no comments for Property HiddenFromAddressListsEnabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("HiddenFromAddressListsEnabled")]
        public virtual global::System.Nullable<bool> HiddenFromAddressListsEnabled
        {
            get
            {
                return this._HiddenFromAddressListsEnabled;
            }
            set
            {
                this.OnHiddenFromAddressListsEnabledChanging(value);
                this._HiddenFromAddressListsEnabled = value;
                this.OnHiddenFromAddressListsEnabledChanged();
                this.OnPropertyChanged("HiddenFromAddressListsEnabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _HiddenFromAddressListsEnabled;
        partial void OnHiddenFromAddressListsEnabledChanging(global::System.Nullable<bool> value);
        partial void OnHiddenFromAddressListsEnabledChanged();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute15 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute15")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute15
        {
            get
            {
                return this._ConditionalCustomAttribute15;
            }
            set
            {
                this.OnConditionalCustomAttribute15Changing(value);
                this._ConditionalCustomAttribute15 = value;
                this.OnConditionalCustomAttribute15Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute15");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute15 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute15Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute15Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute14 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute14")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute14
        {
            get
            {
                return this._ConditionalCustomAttribute14;
            }
            set
            {
                this.OnConditionalCustomAttribute14Changing(value);
                this._ConditionalCustomAttribute14 = value;
                this.OnConditionalCustomAttribute14Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute14");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute14 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute14Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute14Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute13 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute13")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute13
        {
            get
            {
                return this._ConditionalCustomAttribute13;
            }
            set
            {
                this.OnConditionalCustomAttribute13Changing(value);
                this._ConditionalCustomAttribute13 = value;
                this.OnConditionalCustomAttribute13Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute13");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute13 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute13Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute13Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute12 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute12")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute12
        {
            get
            {
                return this._ConditionalCustomAttribute12;
            }
            set
            {
                this.OnConditionalCustomAttribute12Changing(value);
                this._ConditionalCustomAttribute12 = value;
                this.OnConditionalCustomAttribute12Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute12");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute12 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute12Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute12Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute11 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute11")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute11
        {
            get
            {
                return this._ConditionalCustomAttribute11;
            }
            set
            {
                this.OnConditionalCustomAttribute11Changing(value);
                this._ConditionalCustomAttribute11 = value;
                this.OnConditionalCustomAttribute11Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute11");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute11 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute11Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute11Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute10 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute10")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute10
        {
            get
            {
                return this._ConditionalCustomAttribute10;
            }
            set
            {
                this.OnConditionalCustomAttribute10Changing(value);
                this._ConditionalCustomAttribute10 = value;
                this.OnConditionalCustomAttribute10Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute10");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute10 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute10Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute10Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute9 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute9")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute9
        {
            get
            {
                return this._ConditionalCustomAttribute9;
            }
            set
            {
                this.OnConditionalCustomAttribute9Changing(value);
                this._ConditionalCustomAttribute9 = value;
                this.OnConditionalCustomAttribute9Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute9");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute9 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute9Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute9Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute8 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute8")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute8
        {
            get
            {
                return this._ConditionalCustomAttribute8;
            }
            set
            {
                this.OnConditionalCustomAttribute8Changing(value);
                this._ConditionalCustomAttribute8 = value;
                this.OnConditionalCustomAttribute8Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute8");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute8 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute8Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute8Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute7 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute7")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute7
        {
            get
            {
                return this._ConditionalCustomAttribute7;
            }
            set
            {
                this.OnConditionalCustomAttribute7Changing(value);
                this._ConditionalCustomAttribute7 = value;
                this.OnConditionalCustomAttribute7Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute7");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute7 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute7Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute7Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute6 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute6")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute6
        {
            get
            {
                return this._ConditionalCustomAttribute6;
            }
            set
            {
                this.OnConditionalCustomAttribute6Changing(value);
                this._ConditionalCustomAttribute6 = value;
                this.OnConditionalCustomAttribute6Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute6");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute6 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute6Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute6Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute5 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute5")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute5
        {
            get
            {
                return this._ConditionalCustomAttribute5;
            }
            set
            {
                this.OnConditionalCustomAttribute5Changing(value);
                this._ConditionalCustomAttribute5 = value;
                this.OnConditionalCustomAttribute5Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute5");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute5 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute5Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute5Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute4 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute4")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute4
        {
            get
            {
                return this._ConditionalCustomAttribute4;
            }
            set
            {
                this.OnConditionalCustomAttribute4Changing(value);
                this._ConditionalCustomAttribute4 = value;
                this.OnConditionalCustomAttribute4Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute4");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute4 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute4Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute4Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute3")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute3
        {
            get
            {
                return this._ConditionalCustomAttribute3;
            }
            set
            {
                this.OnConditionalCustomAttribute3Changing(value);
                this._ConditionalCustomAttribute3 = value;
                this.OnConditionalCustomAttribute3Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute3 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute3Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute3Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute2")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute2
        {
            get
            {
                return this._ConditionalCustomAttribute2;
            }
            set
            {
                this.OnConditionalCustomAttribute2Changing(value);
                this._ConditionalCustomAttribute2 = value;
                this.OnConditionalCustomAttribute2Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute2 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute2Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute2Changed();
        /// <summary>
        /// There are no comments for Property ConditionalCustomAttribute1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCustomAttribute1")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCustomAttribute1
        {
            get
            {
                return this._ConditionalCustomAttribute1;
            }
            set
            {
                this.OnConditionalCustomAttribute1Changing(value);
                this._ConditionalCustomAttribute1 = value;
                this.OnConditionalCustomAttribute1Changed();
                this.OnPropertyChanged("ConditionalCustomAttribute1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCustomAttribute1 = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCustomAttribute1Changing(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCustomAttribute1Changed();
        /// <summary>
        /// There are no comments for Property ConditionalStateOrProvince in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalStateOrProvince")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalStateOrProvince
        {
            get
            {
                return this._ConditionalStateOrProvince;
            }
            set
            {
                this.OnConditionalStateOrProvinceChanging(value);
                this._ConditionalStateOrProvince = value;
                this.OnConditionalStateOrProvinceChanged();
                this.OnPropertyChanged("ConditionalStateOrProvince");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalStateOrProvince = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalStateOrProvinceChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalStateOrProvinceChanged();
        /// <summary>
        /// There are no comments for Property ConditionalCompany in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalCompany")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalCompany
        {
            get
            {
                return this._ConditionalCompany;
            }
            set
            {
                this.OnConditionalCompanyChanging(value);
                this._ConditionalCompany = value;
                this.OnConditionalCompanyChanged();
                this.OnPropertyChanged("ConditionalCompany");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalCompany = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalCompanyChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalCompanyChanged();
        /// <summary>
        /// There are no comments for Property ConditionalDepartment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConditionalDepartment")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ConditionalDepartment
        {
            get
            {
                return this._ConditionalDepartment;
            }
            set
            {
                this.OnConditionalDepartmentChanging(value);
                this._ConditionalDepartment = value;
                this.OnConditionalDepartmentChanged();
                this.OnPropertyChanged("ConditionalDepartment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ConditionalDepartment = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnConditionalDepartmentChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnConditionalDepartmentChanged();
        /// <summary>
        /// There are no comments for Property AcceptMessagesOnlyFromSendersOrMembers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AcceptMessagesOnlyFromSendersOrMembers")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> AcceptMessagesOnlyFromSendersOrMembers
        {
            get
            {
                return this._AcceptMessagesOnlyFromSendersOrMembers;
            }
            set
            {
                this.OnAcceptMessagesOnlyFromSendersOrMembersChanging(value);
                this._AcceptMessagesOnlyFromSendersOrMembers = value;
                this.OnAcceptMessagesOnlyFromSendersOrMembersChanged();
                this.OnPropertyChanged("AcceptMessagesOnlyFromSendersOrMembers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _AcceptMessagesOnlyFromSendersOrMembers = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnAcceptMessagesOnlyFromSendersOrMembersChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnAcceptMessagesOnlyFromSendersOrMembersChanged();
        /// <summary>
        /// There are no comments for Property RequireSenderAuthenticationEnabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RequireSenderAuthenticationEnabled")]
        public virtual global::System.Nullable<bool> RequireSenderAuthenticationEnabled
        {
            get
            {
                return this._RequireSenderAuthenticationEnabled;
            }
            set
            {
                this.OnRequireSenderAuthenticationEnabledChanging(value);
                this._RequireSenderAuthenticationEnabled = value;
                this.OnRequireSenderAuthenticationEnabledChanged();
                this.OnPropertyChanged("RequireSenderAuthenticationEnabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _RequireSenderAuthenticationEnabled;
        partial void OnRequireSenderAuthenticationEnabledChanging(global::System.Nullable<bool> value);
        partial void OnRequireSenderAuthenticationEnabledChanged();
        /// <summary>
        /// There are no comments for Property ModerationEnabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModerationEnabled")]
        public virtual global::System.Nullable<bool> ModerationEnabled
        {
            get
            {
                return this._ModerationEnabled;
            }
            set
            {
                this.OnModerationEnabledChanging(value);
                this._ModerationEnabled = value;
                this.OnModerationEnabledChanged();
                this.OnPropertyChanged("ModerationEnabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _ModerationEnabled;
        partial void OnModerationEnabledChanging(global::System.Nullable<bool> value);
        partial void OnModerationEnabledChanged();
        /// <summary>
        /// There are no comments for Property ModeratedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ModeratedBy")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> ModeratedBy
        {
            get
            {
                return this._ModeratedBy;
            }
            set
            {
                this.OnModeratedByChanging(value);
                this._ModeratedBy = value;
                this.OnModeratedByChanged();
                this.OnPropertyChanged("ModeratedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _ModeratedBy = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnModeratedByChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnModeratedByChanged();
        /// <summary>
        /// There are no comments for Property BypassModerationFromSendersOrMembers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BypassModerationFromSendersOrMembers")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> BypassModerationFromSendersOrMembers
        {
            get
            {
                return this._BypassModerationFromSendersOrMembers;
            }
            set
            {
                this.OnBypassModerationFromSendersOrMembersChanging(value);
                this._BypassModerationFromSendersOrMembers = value;
                this.OnBypassModerationFromSendersOrMembersChanged();
                this.OnPropertyChanged("BypassModerationFromSendersOrMembers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _BypassModerationFromSendersOrMembers = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnBypassModerationFromSendersOrMembersChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnBypassModerationFromSendersOrMembersChanged();
        /// <summary>
        /// There are no comments for Property GrantSendOnBehalfTo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GrantSendOnBehalfTo")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> GrantSendOnBehalfTo
        {
            get
            {
                return this._GrantSendOnBehalfTo;
            }
            set
            {
                this.OnGrantSendOnBehalfToChanging(value);
                this._GrantSendOnBehalfTo = value;
                this.OnGrantSendOnBehalfToChanged();
                this.OnPropertyChanged("GrantSendOnBehalfTo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _GrantSendOnBehalfTo = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnGrantSendOnBehalfToChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnGrantSendOnBehalfToChanged();
        /// <summary>
        /// There are no comments for Property SendModerationNotifications in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SendModerationNotifications")]
        public virtual string SendModerationNotifications
        {
            get
            {
                return this._SendModerationNotifications;
            }
            set
            {
                this.OnSendModerationNotificationsChanging(value);
                this._SendModerationNotifications = value;
                this.OnSendModerationNotificationsChanged();
                this.OnPropertyChanged("SendModerationNotifications");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SendModerationNotifications;
        partial void OnSendModerationNotificationsChanging(string value);
        partial void OnSendModerationNotificationsChanged();
        /// <summary>
        /// There are no comments for Property EmailAddresses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EmailAddresses")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> EmailAddresses
        {
            get
            {
                return this._EmailAddresses;
            }
            set
            {
                this.OnEmailAddressesChanging(value);
                this._EmailAddresses = value;
                this.OnEmailAddressesChanged();
                this.OnPropertyChanged("EmailAddresses");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _EmailAddresses = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnEmailAddressesChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnEmailAddressesChanged();
        /// <summary>
        /// There are no comments for Property SendAsPermissionList in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SendAsPermissionList")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> SendAsPermissionList
        {
            get
            {
                return this._SendAsPermissionList;
            }
            set
            {
                this.OnSendAsPermissionListChanging(value);
                this._SendAsPermissionList = value;
                this.OnSendAsPermissionListChanged();
                this.OnPropertyChanged("SendAsPermissionList");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _SendAsPermissionList = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnSendAsPermissionListChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnSendAsPermissionListChanged();
        /// <summary>
        /// There are no comments for Property WhenChanged in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WhenChanged")]
        public virtual string WhenChanged
        {
            get
            {
                return this._WhenChanged;
            }
            set
            {
                this.OnWhenChangedChanging(value);
                this._WhenChanged = value;
                this.OnWhenChangedChanged();
                this.OnPropertyChanged("WhenChanged");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _WhenChanged;
        partial void OnWhenChangedChanging(string value);
        partial void OnWhenChangedChanged();
        /// <summary>
        /// There are no comments for Property WhenCreated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WhenCreated")]
        public virtual string WhenCreated
        {
            get
            {
                return this._WhenCreated;
            }
            set
            {
                this.OnWhenCreatedChanging(value);
                this._WhenCreated = value;
                this.OnWhenCreatedChanged();
                this.OnPropertyChanged("WhenCreated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _WhenCreated;
        partial void OnWhenCreatedChanging(string value);
        partial void OnWhenCreatedChanged();
        /// <summary>
        /// There are no comments for Property WhenChangedUTC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WhenChangedUTC")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> WhenChangedUTC
        {
            get
            {
                return this._WhenChangedUTC;
            }
            set
            {
                this.OnWhenChangedUTCChanging(value);
                this._WhenChangedUTC = value;
                this.OnWhenChangedUTCChanged();
                this.OnPropertyChanged("WhenChangedUTC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _WhenChangedUTC;
        partial void OnWhenChangedUTCChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnWhenChangedUTCChanged();
        /// <summary>
        /// There are no comments for Property WhenCreatedUTC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WhenCreatedUTC")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> WhenCreatedUTC
        {
            get
            {
                return this._WhenCreatedUTC;
            }
            set
            {
                this.OnWhenCreatedUTCChanging(value);
                this._WhenCreatedUTC = value;
                this.OnWhenCreatedUTCChanged();
                this.OnPropertyChanged("WhenCreatedUTC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _WhenCreatedUTC;
        partial void OnWhenCreatedUTCChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnWhenCreatedUTCChanged();
        /// <summary>
        /// There are no comments for Property RecipientType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RecipientType")]
        public virtual string RecipientType
        {
            get
            {
                return this._RecipientType;
            }
            set
            {
                this.OnRecipientTypeChanging(value);
                this._RecipientType = value;
                this.OnRecipientTypeChanged();
                this.OnPropertyChanged("RecipientType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RecipientType;
        partial void OnRecipientTypeChanging(string value);
        partial void OnRecipientTypeChanged();
        /// <summary>
        /// There are no comments for Property RecipientTypeDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RecipientTypeDetails")]
        public virtual string RecipientTypeDetails
        {
            get
            {
                return this._RecipientTypeDetails;
            }
            set
            {
                this.OnRecipientTypeDetailsChanging(value);
                this._RecipientTypeDetails = value;
                this.OnRecipientTypeDetailsChanged();
                this.OnPropertyChanged("RecipientTypeDetails");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RecipientTypeDetails;
        partial void OnRecipientTypeDetailsChanging(string value);
        partial void OnRecipientTypeDetailsChanged();
        /// <summary>
        /// There are no comments for Property IsValid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsValid")]
        public virtual global::System.Nullable<bool> IsValid
        {
            get
            {
                return this._IsValid;
            }
            set
            {
                this.OnIsValidChanging(value);
                this._IsValid = value;
                this.OnIsValidChanged();
                this.OnPropertyChanged("IsValid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _IsValid;
        partial void OnIsValidChanging(global::System.Nullable<bool> value);
        partial void OnIsValidChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
