//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for EsnLanguage in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EsnLanguage")]
    public enum EsnLanguage : long
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Default")]
        Default = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("English")]
        English = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("French")]
        French = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("German")]
        German = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Italian")]
        Italian = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Japanese")]
        Japanese = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Spanish")]
        Spanish = 6,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Korean")]
        Korean = 7,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Portuguese")]
        Portuguese = 8,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Russian")]
        Russian = 9,
        [global::Microsoft.OData.Client.OriginalNameAttribute("ChineseSimplified")]
        ChineseSimplified = 10,
        [global::Microsoft.OData.Client.OriginalNameAttribute("ChineseTraditional")]
        ChineseTraditional = 11,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Amharic")]
        Amharic = 12,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Arabic")]
        Arabic = 13,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Bulgarian")]
        Bulgarian = 14,
        [global::Microsoft.OData.Client.OriginalNameAttribute("BengaliIndia")]
        BengaliIndia = 15,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Catalan")]
        Catalan = 16,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Czech")]
        Czech = 17,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Cyrillic")]
        Cyrillic = 18,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Danish")]
        Danish = 19,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Greek")]
        Greek = 20,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Estonian")]
        Estonian = 21,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Basque")]
        Basque = 22,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Persian")]
        Persian = 23,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Finnish")]
        Finnish = 24,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Filipino")]
        Filipino = 25,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Galician")]
        Galician = 26,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Gujarati")]
        Gujarati = 27,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Hebrew")]
        Hebrew = 28,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Hindi")]
        Hindi = 29,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Croatian")]
        Croatian = 30,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Hungarian")]
        Hungarian = 31,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Indonesian")]
        Indonesian = 32,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Icelandic")]
        Icelandic = 33,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Kazakh")]
        Kazakh = 34,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Kannada")]
        Kannada = 35,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Lithuanian")]
        Lithuanian = 36,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Latvian")]
        Latvian = 37,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Malayalam")]
        Malayalam = 38,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Marathi")]
        Marathi = 39,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Malay")]
        Malay = 40,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Dutch")]
        Dutch = 41,
        [global::Microsoft.OData.Client.OriginalNameAttribute("NorwegianNynorsk")]
        NorwegianNynorsk = 42,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Norwegian")]
        Norwegian = 43,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Odia")]
        Odia = 44,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Polish")]
        Polish = 45,
        [global::Microsoft.OData.Client.OriginalNameAttribute("PortuguesePortugal")]
        PortuguesePortugal = 46,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Romanian")]
        Romanian = 47,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Slovak")]
        Slovak = 48,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Slovenian")]
        Slovenian = 49,
        [global::Microsoft.OData.Client.OriginalNameAttribute("SerbianCyrillic")]
        SerbianCyrillic = 50,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Serbian")]
        Serbian = 51,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Swedish")]
        Swedish = 52,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Swahili")]
        Swahili = 53,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Tamil")]
        Tamil = 54,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Telugu")]
        Telugu = 55,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Thai")]
        Thai = 56,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Turkish")]
        Turkish = 57,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Ukrainian")]
        Ukrainian = 58,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Urdu")]
        Urdu = 59,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Vietnamese")]
        Vietnamese = 60
    }
}
