//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 3/25/2026 1:02:19 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for GenericHashTable in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("GenericHashTable")]
    public partial class GenericHashTable : OpenComplexEntry
    {
    }
}
