//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for ImpersonationAction in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ImpersonationAction")]
    public enum ImpersonationAction : long
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("NoAction")]
        NoAction = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("MoveToJmf")]
        MoveToJmf = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Redirect")]
        Redirect = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Quarantine")]
        Quarantine = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Delete")]
        Delete = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("BccMessage")]
        BccMessage = 5
    }
}
