//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for ImpersonationProtectionState in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ImpersonationProtectionState")]
    public enum ImpersonationProtectionState : long
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Default")]
        Default = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Automatic")]
        Automatic = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Manual")]
        Manual = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Off")]
        Off = 3
    }
}
