//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 3/25/2026 1:02:19 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for IntraOrgFilterState in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IntraOrgFilterState")]
    public enum IntraOrgFilterState : long
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Default")]
        Default = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Disabled")]
        Disabled = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("HighConfidencePhish")]
        HighConfidencePhish = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Phish")]
        Phish = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("HighConfidenceSpam")]
        HighConfidenceSpam = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Spam")]
        Spam = 5
    }
}
