//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for MailboxFolderSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MailboxFolderSingle")]
    public partial class MailboxFolderSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<MailboxFolder>
    {
        /// <summary>
        /// Initialize a new MailboxFolderSingle object.
        /// </summary>
        public MailboxFolderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MailboxFolderSingle object.
        /// </summary>
        public MailboxFolderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MailboxFolderSingle object.
        /// </summary>
        public MailboxFolderSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<MailboxFolder> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for MailboxFolderPermission in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MailboxFolderPermission")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::AdminApiClient.For.ExchangeOnline.OData.MailboxFolderPermission> MailboxFolderPermission
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._MailboxFolderPermission == null))
                {
                    this._MailboxFolderPermission = Context.CreateQuery<global::AdminApiClient.For.ExchangeOnline.OData.MailboxFolderPermission>(GetPath("MailboxFolderPermission"));
                }
                return this._MailboxFolderPermission;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AdminApiClient.For.ExchangeOnline.OData.MailboxFolderPermission> _MailboxFolderPermission;
    }
    /// <summary>
    /// There are no comments for MailboxFolder in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Identity
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Identity")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("MailboxFolder")]
    public partial class MailboxFolder : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Identity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Identity")]
        public virtual string Identity
        {
            get
            {
                return this._Identity;
            }
            set
            {
                this.OnIdentityChanging(value);
                this._Identity = value;
                this.OnIdentityChanged();
                this.OnPropertyChanged("Identity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Identity;
        partial void OnIdentityChanging(string value);
        partial void OnIdentityChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property MailboxFolderPermission in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("MailboxFolderPermission")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::AdminApiClient.For.ExchangeOnline.OData.MailboxFolderPermission> MailboxFolderPermission
        {
            get
            {
                return this._MailboxFolderPermission;
            }
            set
            {
                this.OnMailboxFolderPermissionChanging(value);
                this._MailboxFolderPermission = value;
                this.OnMailboxFolderPermissionChanged();
                this.OnPropertyChanged("MailboxFolderPermission");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::AdminApiClient.For.ExchangeOnline.OData.MailboxFolderPermission> _MailboxFolderPermission = new global::Microsoft.OData.Client.DataServiceCollection<global::AdminApiClient.For.ExchangeOnline.OData.MailboxFolderPermission>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnMailboxFolderPermissionChanging(global::Microsoft.OData.Client.DataServiceCollection<global::AdminApiClient.For.ExchangeOnline.OData.MailboxFolderPermission> value);
        partial void OnMailboxFolderPermissionChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
