//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for MailboxFolderStatistics in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MailboxFolderStatistics")]
    public partial class MailboxFolderStatistics : ComplexEntry
    {
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property SearchFolder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SearchFolder")]
        public virtual global::System.Nullable<bool> SearchFolder
        {
            get
            {
                return this._SearchFolder;
            }
            set
            {
                this.OnSearchFolderChanging(value);
                this._SearchFolder = value;
                this.OnSearchFolderChanged();
                this.OnPropertyChanged("SearchFolder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _SearchFolder;
        partial void OnSearchFolderChanging(global::System.Nullable<bool> value);
        partial void OnSearchFolderChanged();
        /// <summary>
        /// There are no comments for Property CreationTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreationTime")]
        public virtual string CreationTime
        {
            get
            {
                return this._CreationTime;
            }
            set
            {
                this.OnCreationTimeChanging(value);
                this._CreationTime = value;
                this.OnCreationTimeChanged();
                this.OnPropertyChanged("CreationTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CreationTime;
        partial void OnCreationTimeChanging(string value);
        partial void OnCreationTimeChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LastModifiedTime")]
        public virtual string LastModifiedTime
        {
            get
            {
                return this._LastModifiedTime;
            }
            set
            {
                this.OnLastModifiedTimeChanging(value);
                this._LastModifiedTime = value;
                this.OnLastModifiedTimeChanged();
                this.OnPropertyChanged("LastModifiedTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LastModifiedTime;
        partial void OnLastModifiedTimeChanging(string value);
        partial void OnLastModifiedTimeChanged();
        /// <summary>
        /// There are no comments for Property FolderPath in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FolderPath")]
        public virtual string FolderPath
        {
            get
            {
                return this._FolderPath;
            }
            set
            {
                this.OnFolderPathChanging(value);
                this._FolderPath = value;
                this.OnFolderPathChanged();
                this.OnPropertyChanged("FolderPath");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FolderPath;
        partial void OnFolderPathChanging(string value);
        partial void OnFolderPathChanged();
        /// <summary>
        /// There are no comments for Property FolderId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FolderId")]
        public virtual string FolderId
        {
            get
            {
                return this._FolderId;
            }
            set
            {
                this.OnFolderIdChanging(value);
                this._FolderId = value;
                this.OnFolderIdChanged();
                this.OnPropertyChanged("FolderId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FolderId;
        partial void OnFolderIdChanging(string value);
        partial void OnFolderIdChanged();
        /// <summary>
        /// There are no comments for Property ContentFolder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ContentFolder")]
        public virtual global::System.Nullable<bool> ContentFolder
        {
            get
            {
                return this._ContentFolder;
            }
            set
            {
                this.OnContentFolderChanging(value);
                this._ContentFolder = value;
                this.OnContentFolderChanged();
                this.OnPropertyChanged("ContentFolder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _ContentFolder;
        partial void OnContentFolderChanging(global::System.Nullable<bool> value);
        partial void OnContentFolderChanged();
        /// <summary>
        /// There are no comments for Property ContentMailboxGuid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ContentMailboxGuid")]
        public virtual global::System.Nullable<global::System.Guid> ContentMailboxGuid
        {
            get
            {
                return this._ContentMailboxGuid;
            }
            set
            {
                this.OnContentMailboxGuidChanging(value);
                this._ContentMailboxGuid = value;
                this.OnContentMailboxGuidChanged();
                this.OnPropertyChanged("ContentMailboxGuid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ContentMailboxGuid;
        partial void OnContentMailboxGuidChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnContentMailboxGuidChanged();
        /// <summary>
        /// There are no comments for Property Identity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Identity")]
        public virtual string Identity
        {
            get
            {
                return this._Identity;
            }
            set
            {
                this.OnIdentityChanging(value);
                this._Identity = value;
                this.OnIdentityChanged();
                this.OnPropertyChanged("Identity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Identity;
        partial void OnIdentityChanging(string value);
        partial void OnIdentityChanged();
        /// <summary>
        /// There are no comments for Property FolderType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FolderType")]
        public virtual string FolderType
        {
            get
            {
                return this._FolderType;
            }
            set
            {
                this.OnFolderTypeChanging(value);
                this._FolderType = value;
                this.OnFolderTypeChanged();
                this.OnPropertyChanged("FolderType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FolderType;
        partial void OnFolderTypeChanging(string value);
        partial void OnFolderTypeChanged();
        /// <summary>
        /// There are no comments for Property RawContentMailboxGuid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RawContentMailboxGuid")]
        public virtual global::System.Nullable<global::System.Guid> RawContentMailboxGuid
        {
            get
            {
                return this._RawContentMailboxGuid;
            }
            set
            {
                this.OnRawContentMailboxGuidChanging(value);
                this._RawContentMailboxGuid = value;
                this.OnRawContentMailboxGuidChanged();
                this.OnPropertyChanged("RawContentMailboxGuid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _RawContentMailboxGuid;
        partial void OnRawContentMailboxGuidChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnRawContentMailboxGuidChanged();
        /// <summary>
        /// There are no comments for Property Movable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Movable")]
        public virtual global::System.Nullable<bool> Movable
        {
            get
            {
                return this._Movable;
            }
            set
            {
                this.OnMovableChanging(value);
                this._Movable = value;
                this.OnMovableChanged();
                this.OnPropertyChanged("Movable");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _Movable;
        partial void OnMovableChanging(global::System.Nullable<bool> value);
        partial void OnMovableChanged();
        /// <summary>
        /// There are no comments for Property RecoverableItemsFolder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RecoverableItemsFolder")]
        public virtual global::System.Nullable<bool> RecoverableItemsFolder
        {
            get
            {
                return this._RecoverableItemsFolder;
            }
            set
            {
                this.OnRecoverableItemsFolderChanging(value);
                this._RecoverableItemsFolder = value;
                this.OnRecoverableItemsFolderChanged();
                this.OnPropertyChanged("RecoverableItemsFolder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _RecoverableItemsFolder;
        partial void OnRecoverableItemsFolderChanging(global::System.Nullable<bool> value);
        partial void OnRecoverableItemsFolderChanged();
        /// <summary>
        /// There are no comments for Property AssociatedIPMFolderPath in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AssociatedIPMFolderPath")]
        public virtual string AssociatedIPMFolderPath
        {
            get
            {
                return this._AssociatedIPMFolderPath;
            }
            set
            {
                this.OnAssociatedIPMFolderPathChanging(value);
                this._AssociatedIPMFolderPath = value;
                this.OnAssociatedIPMFolderPathChanged();
                this.OnPropertyChanged("AssociatedIPMFolderPath");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AssociatedIPMFolderPath;
        partial void OnAssociatedIPMFolderPathChanging(string value);
        partial void OnAssociatedIPMFolderPathChanged();
        /// <summary>
        /// There are no comments for Property ContainerClass in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ContainerClass")]
        public virtual string ContainerClass
        {
            get
            {
                return this._ContainerClass;
            }
            set
            {
                this.OnContainerClassChanging(value);
                this._ContainerClass = value;
                this.OnContainerClassChanged();
                this.OnPropertyChanged("ContainerClass");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ContainerClass;
        partial void OnContainerClassChanging(string value);
        partial void OnContainerClassChanged();
        /// <summary>
        /// There are no comments for Property Flags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Flags")]
        public virtual string Flags
        {
            get
            {
                return this._Flags;
            }
            set
            {
                this.OnFlagsChanging(value);
                this._Flags = value;
                this.OnFlagsChanged();
                this.OnPropertyChanged("Flags");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Flags;
        partial void OnFlagsChanging(string value);
        partial void OnFlagsChanged();
        /// <summary>
        /// There are no comments for Property TargetQuota in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TargetQuota")]
        public virtual string TargetQuota
        {
            get
            {
                return this._TargetQuota;
            }
            set
            {
                this.OnTargetQuotaChanging(value);
                this._TargetQuota = value;
                this.OnTargetQuotaChanged();
                this.OnPropertyChanged("TargetQuota");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TargetQuota;
        partial void OnTargetQuotaChanging(string value);
        partial void OnTargetQuotaChanged();
        /// <summary>
        /// There are no comments for Property StorageQuota in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("StorageQuota")]
        public virtual global::System.Nullable<long> StorageQuota
        {
            get
            {
                return this._StorageQuota;
            }
            set
            {
                this.OnStorageQuotaChanging(value);
                this._StorageQuota = value;
                this.OnStorageQuotaChanged();
                this.OnPropertyChanged("StorageQuota");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _StorageQuota;
        partial void OnStorageQuotaChanging(global::System.Nullable<long> value);
        partial void OnStorageQuotaChanged();
        /// <summary>
        /// There are no comments for Property StorageWarningQuota in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("StorageWarningQuota")]
        public virtual global::System.Nullable<long> StorageWarningQuota
        {
            get
            {
                return this._StorageWarningQuota;
            }
            set
            {
                this.OnStorageWarningQuotaChanging(value);
                this._StorageWarningQuota = value;
                this.OnStorageWarningQuotaChanged();
                this.OnPropertyChanged("StorageWarningQuota");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _StorageWarningQuota;
        partial void OnStorageWarningQuotaChanging(global::System.Nullable<long> value);
        partial void OnStorageWarningQuotaChanged();
        /// <summary>
        /// There are no comments for Property VisibleItemsInFolder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("VisibleItemsInFolder")]
        public virtual global::System.Nullable<int> VisibleItemsInFolder
        {
            get
            {
                return this._VisibleItemsInFolder;
            }
            set
            {
                this.OnVisibleItemsInFolderChanging(value);
                this._VisibleItemsInFolder = value;
                this.OnVisibleItemsInFolderChanged();
                this.OnPropertyChanged("VisibleItemsInFolder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _VisibleItemsInFolder;
        partial void OnVisibleItemsInFolderChanging(global::System.Nullable<int> value);
        partial void OnVisibleItemsInFolderChanged();
        /// <summary>
        /// There are no comments for Property HiddenItemsInFolder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("HiddenItemsInFolder")]
        public virtual global::System.Nullable<int> HiddenItemsInFolder
        {
            get
            {
                return this._HiddenItemsInFolder;
            }
            set
            {
                this.OnHiddenItemsInFolderChanging(value);
                this._HiddenItemsInFolder = value;
                this.OnHiddenItemsInFolderChanged();
                this.OnPropertyChanged("HiddenItemsInFolder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _HiddenItemsInFolder;
        partial void OnHiddenItemsInFolderChanging(global::System.Nullable<int> value);
        partial void OnHiddenItemsInFolderChanged();
        /// <summary>
        /// There are no comments for Property ItemsInFolder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ItemsInFolder")]
        public virtual global::System.Nullable<int> ItemsInFolder
        {
            get
            {
                return this._ItemsInFolder;
            }
            set
            {
                this.OnItemsInFolderChanging(value);
                this._ItemsInFolder = value;
                this.OnItemsInFolderChanged();
                this.OnPropertyChanged("ItemsInFolder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ItemsInFolder;
        partial void OnItemsInFolderChanging(global::System.Nullable<int> value);
        partial void OnItemsInFolderChanged();
        /// <summary>
        /// There are no comments for Property DeletedItemsInFolder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeletedItemsInFolder")]
        public virtual global::System.Nullable<int> DeletedItemsInFolder
        {
            get
            {
                return this._DeletedItemsInFolder;
            }
            set
            {
                this.OnDeletedItemsInFolderChanging(value);
                this._DeletedItemsInFolder = value;
                this.OnDeletedItemsInFolderChanged();
                this.OnPropertyChanged("DeletedItemsInFolder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _DeletedItemsInFolder;
        partial void OnDeletedItemsInFolderChanging(global::System.Nullable<int> value);
        partial void OnDeletedItemsInFolderChanged();
        /// <summary>
        /// There are no comments for Property FolderSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FolderSize")]
        public virtual global::System.Nullable<long> FolderSize
        {
            get
            {
                return this._FolderSize;
            }
            set
            {
                this.OnFolderSizeChanging(value);
                this._FolderSize = value;
                this.OnFolderSizeChanged();
                this.OnPropertyChanged("FolderSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _FolderSize;
        partial void OnFolderSizeChanging(global::System.Nullable<long> value);
        partial void OnFolderSizeChanged();
        /// <summary>
        /// There are no comments for Property ItemsInFolderAndSubfolders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ItemsInFolderAndSubfolders")]
        public virtual global::System.Nullable<int> ItemsInFolderAndSubfolders
        {
            get
            {
                return this._ItemsInFolderAndSubfolders;
            }
            set
            {
                this.OnItemsInFolderAndSubfoldersChanging(value);
                this._ItemsInFolderAndSubfolders = value;
                this.OnItemsInFolderAndSubfoldersChanged();
                this.OnPropertyChanged("ItemsInFolderAndSubfolders");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ItemsInFolderAndSubfolders;
        partial void OnItemsInFolderAndSubfoldersChanging(global::System.Nullable<int> value);
        partial void OnItemsInFolderAndSubfoldersChanged();
        /// <summary>
        /// There are no comments for Property DeletedItemsInFolderAndSubfolders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeletedItemsInFolderAndSubfolders")]
        public virtual global::System.Nullable<int> DeletedItemsInFolderAndSubfolders
        {
            get
            {
                return this._DeletedItemsInFolderAndSubfolders;
            }
            set
            {
                this.OnDeletedItemsInFolderAndSubfoldersChanging(value);
                this._DeletedItemsInFolderAndSubfolders = value;
                this.OnDeletedItemsInFolderAndSubfoldersChanged();
                this.OnPropertyChanged("DeletedItemsInFolderAndSubfolders");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _DeletedItemsInFolderAndSubfolders;
        partial void OnDeletedItemsInFolderAndSubfoldersChanging(global::System.Nullable<int> value);
        partial void OnDeletedItemsInFolderAndSubfoldersChanged();
        /// <summary>
        /// There are no comments for Property FolderAndSubfolderSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FolderAndSubfolderSize")]
        public virtual global::System.Nullable<long> FolderAndSubfolderSize
        {
            get
            {
                return this._FolderAndSubfolderSize;
            }
            set
            {
                this.OnFolderAndSubfolderSizeChanging(value);
                this._FolderAndSubfolderSize = value;
                this.OnFolderAndSubfolderSizeChanged();
                this.OnPropertyChanged("FolderAndSubfolderSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _FolderAndSubfolderSize;
        partial void OnFolderAndSubfolderSizeChanging(global::System.Nullable<long> value);
        partial void OnFolderAndSubfolderSizeChanged();
        /// <summary>
        /// There are no comments for Property CurrentSchemaVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrentSchemaVersion")]
        public virtual string CurrentSchemaVersion
        {
            get
            {
                return this._CurrentSchemaVersion;
            }
            set
            {
                this.OnCurrentSchemaVersionChanging(value);
                this._CurrentSchemaVersion = value;
                this.OnCurrentSchemaVersionChanged();
                this.OnPropertyChanged("CurrentSchemaVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CurrentSchemaVersion;
        partial void OnCurrentSchemaVersionChanging(string value);
        partial void OnCurrentSchemaVersionChanged();
        /// <summary>
        /// There are no comments for Property OldestItemReceivedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OldestItemReceivedDate")]
        public virtual string OldestItemReceivedDate
        {
            get
            {
                return this._OldestItemReceivedDate;
            }
            set
            {
                this.OnOldestItemReceivedDateChanging(value);
                this._OldestItemReceivedDate = value;
                this.OnOldestItemReceivedDateChanged();
                this.OnPropertyChanged("OldestItemReceivedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _OldestItemReceivedDate;
        partial void OnOldestItemReceivedDateChanging(string value);
        partial void OnOldestItemReceivedDateChanged();
        /// <summary>
        /// There are no comments for Property NewestItemReceivedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NewestItemReceivedDate")]
        public virtual string NewestItemReceivedDate
        {
            get
            {
                return this._NewestItemReceivedDate;
            }
            set
            {
                this.OnNewestItemReceivedDateChanging(value);
                this._NewestItemReceivedDate = value;
                this.OnNewestItemReceivedDateChanged();
                this.OnPropertyChanged("NewestItemReceivedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _NewestItemReceivedDate;
        partial void OnNewestItemReceivedDateChanging(string value);
        partial void OnNewestItemReceivedDateChanged();
        /// <summary>
        /// There are no comments for Property OldestDeletedItemReceivedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OldestDeletedItemReceivedDate")]
        public virtual string OldestDeletedItemReceivedDate
        {
            get
            {
                return this._OldestDeletedItemReceivedDate;
            }
            set
            {
                this.OnOldestDeletedItemReceivedDateChanging(value);
                this._OldestDeletedItemReceivedDate = value;
                this.OnOldestDeletedItemReceivedDateChanged();
                this.OnPropertyChanged("OldestDeletedItemReceivedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _OldestDeletedItemReceivedDate;
        partial void OnOldestDeletedItemReceivedDateChanging(string value);
        partial void OnOldestDeletedItemReceivedDateChanged();
        /// <summary>
        /// There are no comments for Property NewestDeletedItemReceivedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NewestDeletedItemReceivedDate")]
        public virtual string NewestDeletedItemReceivedDate
        {
            get
            {
                return this._NewestDeletedItemReceivedDate;
            }
            set
            {
                this.OnNewestDeletedItemReceivedDateChanging(value);
                this._NewestDeletedItemReceivedDate = value;
                this.OnNewestDeletedItemReceivedDateChanged();
                this.OnPropertyChanged("NewestDeletedItemReceivedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _NewestDeletedItemReceivedDate;
        partial void OnNewestDeletedItemReceivedDateChanging(string value);
        partial void OnNewestDeletedItemReceivedDateChanged();
        /// <summary>
        /// There are no comments for Property OldestItemLastModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OldestItemLastModifiedDate")]
        public virtual string OldestItemLastModifiedDate
        {
            get
            {
                return this._OldestItemLastModifiedDate;
            }
            set
            {
                this.OnOldestItemLastModifiedDateChanging(value);
                this._OldestItemLastModifiedDate = value;
                this.OnOldestItemLastModifiedDateChanged();
                this.OnPropertyChanged("OldestItemLastModifiedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _OldestItemLastModifiedDate;
        partial void OnOldestItemLastModifiedDateChanging(string value);
        partial void OnOldestItemLastModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property NewestItemLastModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NewestItemLastModifiedDate")]
        public virtual string NewestItemLastModifiedDate
        {
            get
            {
                return this._NewestItemLastModifiedDate;
            }
            set
            {
                this.OnNewestItemLastModifiedDateChanging(value);
                this._NewestItemLastModifiedDate = value;
                this.OnNewestItemLastModifiedDateChanged();
                this.OnPropertyChanged("NewestItemLastModifiedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _NewestItemLastModifiedDate;
        partial void OnNewestItemLastModifiedDateChanging(string value);
        partial void OnNewestItemLastModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property OldestDeletedItemLastModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OldestDeletedItemLastModifiedDate")]
        public virtual string OldestDeletedItemLastModifiedDate
        {
            get
            {
                return this._OldestDeletedItemLastModifiedDate;
            }
            set
            {
                this.OnOldestDeletedItemLastModifiedDateChanging(value);
                this._OldestDeletedItemLastModifiedDate = value;
                this.OnOldestDeletedItemLastModifiedDateChanged();
                this.OnPropertyChanged("OldestDeletedItemLastModifiedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _OldestDeletedItemLastModifiedDate;
        partial void OnOldestDeletedItemLastModifiedDateChanging(string value);
        partial void OnOldestDeletedItemLastModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property NewestDeletedItemLastModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NewestDeletedItemLastModifiedDate")]
        public virtual string NewestDeletedItemLastModifiedDate
        {
            get
            {
                return this._NewestDeletedItemLastModifiedDate;
            }
            set
            {
                this.OnNewestDeletedItemLastModifiedDateChanging(value);
                this._NewestDeletedItemLastModifiedDate = value;
                this.OnNewestDeletedItemLastModifiedDateChanged();
                this.OnPropertyChanged("NewestDeletedItemLastModifiedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _NewestDeletedItemLastModifiedDate;
        partial void OnNewestDeletedItemLastModifiedDateChanging(string value);
        partial void OnNewestDeletedItemLastModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ManagedFolder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ManagedFolder")]
        public virtual string ManagedFolder
        {
            get
            {
                return this._ManagedFolder;
            }
            set
            {
                this.OnManagedFolderChanging(value);
                this._ManagedFolder = value;
                this.OnManagedFolderChanged();
                this.OnPropertyChanged("ManagedFolder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ManagedFolder;
        partial void OnManagedFolderChanging(string value);
        partial void OnManagedFolderChanged();
        /// <summary>
        /// There are no comments for Property DeletePolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeletePolicy")]
        public virtual string DeletePolicy
        {
            get
            {
                return this._DeletePolicy;
            }
            set
            {
                this.OnDeletePolicyChanging(value);
                this._DeletePolicy = value;
                this.OnDeletePolicyChanged();
                this.OnPropertyChanged("DeletePolicy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeletePolicy;
        partial void OnDeletePolicyChanging(string value);
        partial void OnDeletePolicyChanged();
        /// <summary>
        /// There are no comments for Property ArchivePolicy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ArchivePolicy")]
        public virtual string ArchivePolicy
        {
            get
            {
                return this._ArchivePolicy;
            }
            set
            {
                this.OnArchivePolicyChanging(value);
                this._ArchivePolicy = value;
                this.OnArchivePolicyChanged();
                this.OnPropertyChanged("ArchivePolicy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ArchivePolicy;
        partial void OnArchivePolicyChanging(string value);
        partial void OnArchivePolicyChanged();
        /// <summary>
        /// There are no comments for Property TopSubject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopSubject")]
        public virtual string TopSubject
        {
            get
            {
                return this._TopSubject;
            }
            set
            {
                this.OnTopSubjectChanging(value);
                this._TopSubject = value;
                this.OnTopSubjectChanged();
                this.OnPropertyChanged("TopSubject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TopSubject;
        partial void OnTopSubjectChanging(string value);
        partial void OnTopSubjectChanged();
        /// <summary>
        /// There are no comments for Property TopSubjectSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopSubjectSize")]
        public virtual global::System.Nullable<long> TopSubjectSize
        {
            get
            {
                return this._TopSubjectSize;
            }
            set
            {
                this.OnTopSubjectSizeChanging(value);
                this._TopSubjectSize = value;
                this.OnTopSubjectSizeChanged();
                this.OnPropertyChanged("TopSubjectSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _TopSubjectSize;
        partial void OnTopSubjectSizeChanging(global::System.Nullable<long> value);
        partial void OnTopSubjectSizeChanged();
        /// <summary>
        /// There are no comments for Property TopSubjectCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopSubjectCount")]
        public virtual global::System.Nullable<int> TopSubjectCount
        {
            get
            {
                return this._TopSubjectCount;
            }
            set
            {
                this.OnTopSubjectCountChanging(value);
                this._TopSubjectCount = value;
                this.OnTopSubjectCountChanged();
                this.OnPropertyChanged("TopSubjectCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _TopSubjectCount;
        partial void OnTopSubjectCountChanging(global::System.Nullable<int> value);
        partial void OnTopSubjectCountChanged();
        /// <summary>
        /// There are no comments for Property TopSubjectClass in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopSubjectClass")]
        public virtual string TopSubjectClass
        {
            get
            {
                return this._TopSubjectClass;
            }
            set
            {
                this.OnTopSubjectClassChanging(value);
                this._TopSubjectClass = value;
                this.OnTopSubjectClassChanged();
                this.OnPropertyChanged("TopSubjectClass");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TopSubjectClass;
        partial void OnTopSubjectClassChanging(string value);
        partial void OnTopSubjectClassChanged();
        /// <summary>
        /// There are no comments for Property TopSubjectPath in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopSubjectPath")]
        public virtual string TopSubjectPath
        {
            get
            {
                return this._TopSubjectPath;
            }
            set
            {
                this.OnTopSubjectPathChanging(value);
                this._TopSubjectPath = value;
                this.OnTopSubjectPathChanged();
                this.OnPropertyChanged("TopSubjectPath");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TopSubjectPath;
        partial void OnTopSubjectPathChanging(string value);
        partial void OnTopSubjectPathChanged();
        /// <summary>
        /// There are no comments for Property TopSubjectReceivedTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopSubjectReceivedTime")]
        public virtual string TopSubjectReceivedTime
        {
            get
            {
                return this._TopSubjectReceivedTime;
            }
            set
            {
                this.OnTopSubjectReceivedTimeChanging(value);
                this._TopSubjectReceivedTime = value;
                this.OnTopSubjectReceivedTimeChanged();
                this.OnPropertyChanged("TopSubjectReceivedTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TopSubjectReceivedTime;
        partial void OnTopSubjectReceivedTimeChanging(string value);
        partial void OnTopSubjectReceivedTimeChanged();
        /// <summary>
        /// There are no comments for Property TopSubjectFrom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopSubjectFrom")]
        public virtual string TopSubjectFrom
        {
            get
            {
                return this._TopSubjectFrom;
            }
            set
            {
                this.OnTopSubjectFromChanging(value);
                this._TopSubjectFrom = value;
                this.OnTopSubjectFromChanged();
                this.OnPropertyChanged("TopSubjectFrom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TopSubjectFrom;
        partial void OnTopSubjectFromChanging(string value);
        partial void OnTopSubjectFromChanged();
        /// <summary>
        /// There are no comments for Property TopClientInfoForSubject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopClientInfoForSubject")]
        public virtual string TopClientInfoForSubject
        {
            get
            {
                return this._TopClientInfoForSubject;
            }
            set
            {
                this.OnTopClientInfoForSubjectChanging(value);
                this._TopClientInfoForSubject = value;
                this.OnTopClientInfoForSubjectChanged();
                this.OnPropertyChanged("TopClientInfoForSubject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TopClientInfoForSubject;
        partial void OnTopClientInfoForSubjectChanging(string value);
        partial void OnTopClientInfoForSubjectChanged();
        /// <summary>
        /// There are no comments for Property TopClientInfoCountForSubject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopClientInfoCountForSubject")]
        public virtual global::System.Nullable<int> TopClientInfoCountForSubject
        {
            get
            {
                return this._TopClientInfoCountForSubject;
            }
            set
            {
                this.OnTopClientInfoCountForSubjectChanging(value);
                this._TopClientInfoCountForSubject = value;
                this.OnTopClientInfoCountForSubjectChanged();
                this.OnPropertyChanged("TopClientInfoCountForSubject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _TopClientInfoCountForSubject;
        partial void OnTopClientInfoCountForSubjectChanging(global::System.Nullable<int> value);
        partial void OnTopClientInfoCountForSubjectChanged();
        /// <summary>
        /// There are no comments for Property SearchFolders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SearchFolders")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> SearchFolders
        {
            get
            {
                return this._SearchFolders;
            }
            set
            {
                this.OnSearchFoldersChanging(value);
                this._SearchFolders = value;
                this.OnSearchFoldersChanged();
                this.OnPropertyChanged("SearchFolders");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _SearchFolders = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnSearchFoldersChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnSearchFoldersChanged();
        /// <summary>
        /// There are no comments for Property AuditAuxMailboxGuid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AuditAuxMailboxGuid")]
        public virtual string AuditAuxMailboxGuid
        {
            get
            {
                return this._AuditAuxMailboxGuid;
            }
            set
            {
                this.OnAuditAuxMailboxGuidChanging(value);
                this._AuditAuxMailboxGuid = value;
                this.OnAuditAuxMailboxGuidChanged();
                this.OnPropertyChanged("AuditAuxMailboxGuid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AuditAuxMailboxGuid;
        partial void OnAuditAuxMailboxGuidChanging(string value);
        partial void OnAuditAuxMailboxGuidChanged();
        /// <summary>
        /// There are no comments for Property AuditFolderStubSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AuditFolderStubSize")]
        public virtual string AuditFolderStubSize
        {
            get
            {
                return this._AuditFolderStubSize;
            }
            set
            {
                this.OnAuditFolderStubSizeChanging(value);
                this._AuditFolderStubSize = value;
                this.OnAuditFolderStubSizeChanged();
                this.OnPropertyChanged("AuditFolderStubSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AuditFolderStubSize;
        partial void OnAuditFolderStubSizeChanging(string value);
        partial void OnAuditFolderStubSizeChanged();
        /// <summary>
        /// There are no comments for Property LastMovedTimeStamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LastMovedTimeStamp")]
        public virtual string LastMovedTimeStamp
        {
            get
            {
                return this._LastMovedTimeStamp;
            }
            set
            {
                this.OnLastMovedTimeStampChanging(value);
                this._LastMovedTimeStamp = value;
                this.OnLastMovedTimeStampChanged();
                this.OnPropertyChanged("LastMovedTimeStamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LastMovedTimeStamp;
        partial void OnLastMovedTimeStampChanging(string value);
        partial void OnLastMovedTimeStampChanged();
        /// <summary>
        /// There are no comments for Property LowLatencyContainerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LowLatencyContainerId")]
        public virtual global::System.Nullable<global::System.Guid> LowLatencyContainerId
        {
            get
            {
                return this._LowLatencyContainerId;
            }
            set
            {
                this.OnLowLatencyContainerIdChanging(value);
                this._LowLatencyContainerId = value;
                this.OnLowLatencyContainerIdChanged();
                this.OnPropertyChanged("LowLatencyContainerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _LowLatencyContainerId;
        partial void OnLowLatencyContainerIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnLowLatencyContainerIdChanged();
        /// <summary>
        /// There are no comments for Property LowLatencyContainerFlags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LowLatencyContainerFlags")]
        public virtual string LowLatencyContainerFlags
        {
            get
            {
                return this._LowLatencyContainerFlags;
            }
            set
            {
                this.OnLowLatencyContainerFlagsChanging(value);
                this._LowLatencyContainerFlags = value;
                this.OnLowLatencyContainerFlagsChanged();
                this.OnPropertyChanged("LowLatencyContainerFlags");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LowLatencyContainerFlags;
        partial void OnLowLatencyContainerFlagsChanging(string value);
        partial void OnLowLatencyContainerFlagsChanged();
        /// <summary>
        /// There are no comments for Property LowLatencyContainerQuota in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LowLatencyContainerQuota")]
        public virtual global::System.Nullable<long> LowLatencyContainerQuota
        {
            get
            {
                return this._LowLatencyContainerQuota;
            }
            set
            {
                this.OnLowLatencyContainerQuotaChanging(value);
                this._LowLatencyContainerQuota = value;
                this.OnLowLatencyContainerQuotaChanged();
                this.OnPropertyChanged("LowLatencyContainerQuota");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _LowLatencyContainerQuota;
        partial void OnLowLatencyContainerQuotaChanging(global::System.Nullable<long> value);
        partial void OnLowLatencyContainerQuotaChanged();
        /// <summary>
        /// There are no comments for Property Diagnostics in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Diagnostics")]
        public virtual string Diagnostics
        {
            get
            {
                return this._Diagnostics;
            }
            set
            {
                this.OnDiagnosticsChanging(value);
                this._Diagnostics = value;
                this.OnDiagnosticsChanged();
                this.OnPropertyChanged("Diagnostics");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Diagnostics;
        partial void OnDiagnosticsChanging(string value);
        partial void OnDiagnosticsChanged();
        /// <summary>
        /// There are no comments for Property DiagnosticInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DiagnosticInfo")]
        public virtual string DiagnosticInfo
        {
            get
            {
                return this._DiagnosticInfo;
            }
            set
            {
                this.OnDiagnosticInfoChanging(value);
                this._DiagnosticInfo = value;
                this.OnDiagnosticInfoChanged();
                this.OnPropertyChanged("DiagnosticInfo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DiagnosticInfo;
        partial void OnDiagnosticInfoChanging(string value);
        partial void OnDiagnosticInfoChanged();
    }
}
