//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for MessageTrace in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MessageTrace")]
    public partial class MessageTrace : ComplexEntry
    {
        /// <summary>
        /// There are no comments for Property MessageId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("MessageId")]
        public virtual string MessageId
        {
            get
            {
                return this._MessageId;
            }
            set
            {
                this.OnMessageIdChanging(value);
                this._MessageId = value;
                this.OnMessageIdChanged();
                this.OnPropertyChanged("MessageId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _MessageId;
        partial void OnMessageIdChanging(string value);
        partial void OnMessageIdChanged();
        /// <summary>
        /// There are no comments for Property Received in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Received")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> Received
        {
            get
            {
                return this._Received;
            }
            set
            {
                this.OnReceivedChanging(value);
                this._Received = value;
                this.OnReceivedChanged();
                this.OnPropertyChanged("Received");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _Received;
        partial void OnReceivedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnReceivedChanged();
        /// <summary>
        /// There are no comments for Property SenderAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SenderAddress")]
        public virtual string SenderAddress
        {
            get
            {
                return this._SenderAddress;
            }
            set
            {
                this.OnSenderAddressChanging(value);
                this._SenderAddress = value;
                this.OnSenderAddressChanged();
                this.OnPropertyChanged("SenderAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SenderAddress;
        partial void OnSenderAddressChanging(string value);
        partial void OnSenderAddressChanged();
        /// <summary>
        /// There are no comments for Property RecipientAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RecipientAddress")]
        public virtual string RecipientAddress
        {
            get
            {
                return this._RecipientAddress;
            }
            set
            {
                this.OnRecipientAddressChanging(value);
                this._RecipientAddress = value;
                this.OnRecipientAddressChanged();
                this.OnPropertyChanged("RecipientAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RecipientAddress;
        partial void OnRecipientAddressChanging(string value);
        partial void OnRecipientAddressChanged();
        /// <summary>
        /// There are no comments for Property Subject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Subject")]
        public virtual string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this._Subject = value;
                this.OnSubjectChanged();
                this.OnPropertyChanged("Subject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public virtual string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property ToIP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ToIP")]
        public virtual string ToIP
        {
            get
            {
                return this._ToIP;
            }
            set
            {
                this.OnToIPChanging(value);
                this._ToIP = value;
                this.OnToIPChanged();
                this.OnPropertyChanged("ToIP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ToIP;
        partial void OnToIPChanging(string value);
        partial void OnToIPChanged();
        /// <summary>
        /// There are no comments for Property FromIP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FromIP")]
        public virtual string FromIP
        {
            get
            {
                return this._FromIP;
            }
            set
            {
                this.OnFromIPChanging(value);
                this._FromIP = value;
                this.OnFromIPChanged();
                this.OnPropertyChanged("FromIP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FromIP;
        partial void OnFromIPChanging(string value);
        partial void OnFromIPChanged();
        /// <summary>
        /// There are no comments for Property Size in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Size")]
        public virtual global::System.Nullable<int> Size
        {
            get
            {
                return this._Size;
            }
            set
            {
                this.OnSizeChanging(value);
                this._Size = value;
                this.OnSizeChanged();
                this.OnPropertyChanged("Size");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Size;
        partial void OnSizeChanging(global::System.Nullable<int> value);
        partial void OnSizeChanged();
        /// <summary>
        /// There are no comments for Property MessageTraceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("MessageTraceId")]
        public virtual global::System.Nullable<global::System.Guid> MessageTraceId
        {
            get
            {
                return this._MessageTraceId;
            }
            set
            {
                this.OnMessageTraceIdChanging(value);
                this._MessageTraceId = value;
                this.OnMessageTraceIdChanged();
                this.OnPropertyChanged("MessageTraceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _MessageTraceId;
        partial void OnMessageTraceIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnMessageTraceIdChanged();
    }
}
