//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for RecipientPermissionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RecipientPermissionSingle")]
    public partial class RecipientPermissionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RecipientPermission>
    {
        /// <summary>
        /// Initialize a new RecipientPermissionSingle object.
        /// </summary>
        public RecipientPermissionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RecipientPermissionSingle object.
        /// </summary>
        public RecipientPermissionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RecipientPermissionSingle object.
        /// </summary>
        public RecipientPermissionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RecipientPermission> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for RecipientPermission in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Trustee
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Trustee")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("RecipientPermission")]
    public partial class RecipientPermission : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Identity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Identity")]
        public virtual string Identity
        {
            get
            {
                return this._Identity;
            }
            set
            {
                this.OnIdentityChanging(value);
                this._Identity = value;
                this.OnIdentityChanged();
                this.OnPropertyChanged("Identity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Identity;
        partial void OnIdentityChanging(string value);
        partial void OnIdentityChanged();
        /// <summary>
        /// There are no comments for Property Trustee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Trustee")]
        public virtual string Trustee
        {
            get
            {
                return this._Trustee;
            }
            set
            {
                this.OnTrusteeChanging(value);
                this._Trustee = value;
                this.OnTrusteeChanged();
                this.OnPropertyChanged("Trustee");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Trustee;
        partial void OnTrusteeChanging(string value);
        partial void OnTrusteeChanged();
        /// <summary>
        /// There are no comments for Property AccessControlType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AccessControlType")]
        public virtual string AccessControlType
        {
            get
            {
                return this._AccessControlType;
            }
            set
            {
                this.OnAccessControlTypeChanging(value);
                this._AccessControlType = value;
                this.OnAccessControlTypeChanged();
                this.OnPropertyChanged("AccessControlType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AccessControlType;
        partial void OnAccessControlTypeChanging(string value);
        partial void OnAccessControlTypeChanged();
        /// <summary>
        /// There are no comments for Property AccessRights in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AccessRights")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<global::AdminApiClient.For.ExchangeOnline.OData.RecipientAccessRight> AccessRights
        {
            get
            {
                return this._AccessRights;
            }
            set
            {
                this.OnAccessRightsChanging(value);
                this._AccessRights = value;
                this.OnAccessRightsChanged();
                this.OnPropertyChanged("AccessRights");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<global::AdminApiClient.For.ExchangeOnline.OData.RecipientAccessRight> _AccessRights = new global::System.Collections.ObjectModel.ObservableCollection<global::AdminApiClient.For.ExchangeOnline.OData.RecipientAccessRight>();
        partial void OnAccessRightsChanging(global::System.Collections.ObjectModel.ObservableCollection<global::AdminApiClient.For.ExchangeOnline.OData.RecipientAccessRight> value);
        partial void OnAccessRightsChanged();
        /// <summary>
        /// There are no comments for Property IsInherited in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsInherited")]
        public virtual global::System.Nullable<bool> IsInherited
        {
            get
            {
                return this._IsInherited;
            }
            set
            {
                this.OnIsInheritedChanging(value);
                this._IsInherited = value;
                this.OnIsInheritedChanged();
                this.OnPropertyChanged("IsInherited");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _IsInherited;
        partial void OnIsInheritedChanging(global::System.Nullable<bool> value);
        partial void OnIsInheritedChanged();
        /// <summary>
        /// There are no comments for Property InheritanceType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("InheritanceType")]
        public virtual string InheritanceType
        {
            get
            {
                return this._InheritanceType;
            }
            set
            {
                this.OnInheritanceTypeChanging(value);
                this._InheritanceType = value;
                this.OnInheritanceTypeChanged();
                this.OnPropertyChanged("InheritanceType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _InheritanceType;
        partial void OnInheritanceTypeChanging(string value);
        partial void OnInheritanceTypeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
