//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/31/2023 2:36:10 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for SafeLinksPolicyPresentationSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SafeLinksPolicyPresentationSingle")]
    public partial class SafeLinksPolicyPresentationSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<SafeLinksPolicyPresentation>
    {
        /// <summary>
        /// Initialize a new SafeLinksPolicyPresentationSingle object.
        /// </summary>
        public SafeLinksPolicyPresentationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SafeLinksPolicyPresentationSingle object.
        /// </summary>
        public SafeLinksPolicyPresentationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new SafeLinksPolicyPresentationSingle object.
        /// </summary>
        public SafeLinksPolicyPresentationSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<SafeLinksPolicyPresentation> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for SafeLinksPolicyPresentation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Identity
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Identity")]
    [global::Microsoft.OData.Client.EntitySet("SafeLinksPolicyPresentation")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("SafeLinksPolicyPresentation")]
    public partial class SafeLinksPolicyPresentation : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Identity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Identity")]
        public virtual string Identity
        {
            get
            {
                return this._Identity;
            }
            set
            {
                this.OnIdentityChanging(value);
                this._Identity = value;
                this.OnIdentityChanged();
                this.OnPropertyChanged("Identity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Identity;
        partial void OnIdentityChanging(string value);
        partial void OnIdentityChanged();
        /// <summary>
        /// There are no comments for Property TrackClicks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TrackClicks")]
        public virtual global::System.Nullable<bool> TrackClicks
        {
            get
            {
                return this._TrackClicks;
            }
            set
            {
                this.OnTrackClicksChanging(value);
                this._TrackClicks = value;
                this.OnTrackClicksChanged();
                this.OnPropertyChanged("TrackClicks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _TrackClicks;
        partial void OnTrackClicksChanging(global::System.Nullable<bool> value);
        partial void OnTrackClicksChanged();
        /// <summary>
        /// There are no comments for Property AllowClickThrough in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AllowClickThrough")]
        public virtual global::System.Nullable<bool> AllowClickThrough
        {
            get
            {
                return this._AllowClickThrough;
            }
            set
            {
                this.OnAllowClickThroughChanging(value);
                this._AllowClickThrough = value;
                this.OnAllowClickThroughChanged();
                this.OnPropertyChanged("AllowClickThrough");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _AllowClickThrough;
        partial void OnAllowClickThroughChanging(global::System.Nullable<bool> value);
        partial void OnAllowClickThroughChanged();
        /// <summary>
        /// There are no comments for Property ScanUrls in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ScanUrls")]
        public virtual global::System.Nullable<bool> ScanUrls
        {
            get
            {
                return this._ScanUrls;
            }
            set
            {
                this.OnScanUrlsChanging(value);
                this._ScanUrls = value;
                this.OnScanUrlsChanged();
                this.OnPropertyChanged("ScanUrls");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _ScanUrls;
        partial void OnScanUrlsChanging(global::System.Nullable<bool> value);
        partial void OnScanUrlsChanged();
        /// <summary>
        /// There are no comments for Property EnableForInternalSenders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EnableForInternalSenders")]
        public virtual global::System.Nullable<bool> EnableForInternalSenders
        {
            get
            {
                return this._EnableForInternalSenders;
            }
            set
            {
                this.OnEnableForInternalSendersChanging(value);
                this._EnableForInternalSenders = value;
                this.OnEnableForInternalSendersChanged();
                this.OnPropertyChanged("EnableForInternalSenders");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _EnableForInternalSenders;
        partial void OnEnableForInternalSendersChanging(global::System.Nullable<bool> value);
        partial void OnEnableForInternalSendersChanged();
        /// <summary>
        /// There are no comments for Property DeliverMessageAfterScan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliverMessageAfterScan")]
        public virtual global::System.Nullable<bool> DeliverMessageAfterScan
        {
            get
            {
                return this._DeliverMessageAfterScan;
            }
            set
            {
                this.OnDeliverMessageAfterScanChanging(value);
                this._DeliverMessageAfterScan = value;
                this.OnDeliverMessageAfterScanChanged();
                this.OnPropertyChanged("DeliverMessageAfterScan");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _DeliverMessageAfterScan;
        partial void OnDeliverMessageAfterScanChanging(global::System.Nullable<bool> value);
        partial void OnDeliverMessageAfterScanChanged();
        /// <summary>
        /// There are no comments for Property DoNotRewriteUrls in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DoNotRewriteUrls")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<string> DoNotRewriteUrls
        {
            get
            {
                return this._DoNotRewriteUrls;
            }
            set
            {
                this.OnDoNotRewriteUrlsChanging(value);
                this._DoNotRewriteUrls = value;
                this.OnDoNotRewriteUrlsChanged();
                this.OnPropertyChanged("DoNotRewriteUrls");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _DoNotRewriteUrls = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnDoNotRewriteUrlsChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnDoNotRewriteUrlsChanged();
        /// <summary>
        /// There are no comments for Property AdminDisplayName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AdminDisplayName")]
        public virtual string AdminDisplayName
        {
            get
            {
                return this._AdminDisplayName;
            }
            set
            {
                this.OnAdminDisplayNameChanging(value);
                this._AdminDisplayName = value;
                this.OnAdminDisplayNameChanged();
                this.OnPropertyChanged("AdminDisplayName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AdminDisplayName;
        partial void OnAdminDisplayNameChanging(string value);
        partial void OnAdminDisplayNameChanged();
        /// <summary>
        /// There are no comments for Property EnableSafeLinksForEmail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EnableSafeLinksForEmail")]
        public virtual global::System.Nullable<bool> EnableSafeLinksForEmail
        {
            get
            {
                return this._EnableSafeLinksForEmail;
            }
            set
            {
                this.OnEnableSafeLinksForEmailChanging(value);
                this._EnableSafeLinksForEmail = value;
                this.OnEnableSafeLinksForEmailChanged();
                this.OnPropertyChanged("EnableSafeLinksForEmail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _EnableSafeLinksForEmail;
        partial void OnEnableSafeLinksForEmailChanging(global::System.Nullable<bool> value);
        partial void OnEnableSafeLinksForEmailChanged();
        /// <summary>
        /// There are no comments for Property EnableSafeLinksForTeams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EnableSafeLinksForTeams")]
        public virtual global::System.Nullable<bool> EnableSafeLinksForTeams
        {
            get
            {
                return this._EnableSafeLinksForTeams;
            }
            set
            {
                this.OnEnableSafeLinksForTeamsChanging(value);
                this._EnableSafeLinksForTeams = value;
                this.OnEnableSafeLinksForTeamsChanged();
                this.OnPropertyChanged("EnableSafeLinksForTeams");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _EnableSafeLinksForTeams;
        partial void OnEnableSafeLinksForTeamsChanging(global::System.Nullable<bool> value);
        partial void OnEnableSafeLinksForTeamsChanged();
        /// <summary>
        /// There are no comments for Property EnableSafeLinksForOffice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EnableSafeLinksForOffice")]
        public virtual global::System.Nullable<bool> EnableSafeLinksForOffice
        {
            get
            {
                return this._EnableSafeLinksForOffice;
            }
            set
            {
                this.OnEnableSafeLinksForOfficeChanging(value);
                this._EnableSafeLinksForOffice = value;
                this.OnEnableSafeLinksForOfficeChanged();
                this.OnPropertyChanged("EnableSafeLinksForOffice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _EnableSafeLinksForOffice;
        partial void OnEnableSafeLinksForOfficeChanging(global::System.Nullable<bool> value);
        partial void OnEnableSafeLinksForOfficeChanged();
        /// <summary>
        /// There are no comments for Property DisableUrlRewrite in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DisableUrlRewrite")]
        public virtual global::System.Nullable<bool> DisableUrlRewrite
        {
            get
            {
                return this._DisableUrlRewrite;
            }
            set
            {
                this.OnDisableUrlRewriteChanging(value);
                this._DisableUrlRewrite = value;
                this.OnDisableUrlRewriteChanged();
                this.OnPropertyChanged("DisableUrlRewrite");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _DisableUrlRewrite;
        partial void OnDisableUrlRewriteChanging(global::System.Nullable<bool> value);
        partial void OnDisableUrlRewriteChanged();
        /// <summary>
        /// There are no comments for Property CustomNotificationText in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CustomNotificationText")]
        public virtual string CustomNotificationText
        {
            get
            {
                return this._CustomNotificationText;
            }
            set
            {
                this.OnCustomNotificationTextChanging(value);
                this._CustomNotificationText = value;
                this.OnCustomNotificationTextChanged();
                this.OnPropertyChanged("CustomNotificationText");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CustomNotificationText;
        partial void OnCustomNotificationTextChanging(string value);
        partial void OnCustomNotificationTextChanged();
        /// <summary>
        /// There are no comments for Property EnableOrganizationBranding in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EnableOrganizationBranding")]
        public virtual global::System.Nullable<bool> EnableOrganizationBranding
        {
            get
            {
                return this._EnableOrganizationBranding;
            }
            set
            {
                this.OnEnableOrganizationBrandingChanging(value);
                this._EnableOrganizationBranding = value;
                this.OnEnableOrganizationBrandingChanged();
                this.OnPropertyChanged("EnableOrganizationBranding");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _EnableOrganizationBranding;
        partial void OnEnableOrganizationBrandingChanging(global::System.Nullable<bool> value);
        partial void OnEnableOrganizationBrandingChanged();
        /// <summary>
        /// There are no comments for Property RecommendedPolicyType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RecommendedPolicyType")]
        public virtual global::System.Nullable<global::AdminApiClient.For.ExchangeOnline.OData.RecommendedPolicyType> RecommendedPolicyType
        {
            get
            {
                return this._RecommendedPolicyType;
            }
            set
            {
                this.OnRecommendedPolicyTypeChanging(value);
                this._RecommendedPolicyType = value;
                this.OnRecommendedPolicyTypeChanged();
                this.OnPropertyChanged("RecommendedPolicyType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::AdminApiClient.For.ExchangeOnline.OData.RecommendedPolicyType> _RecommendedPolicyType;
        partial void OnRecommendedPolicyTypeChanging(global::System.Nullable<global::AdminApiClient.For.ExchangeOnline.OData.RecommendedPolicyType> value);
        partial void OnRecommendedPolicyTypeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property WhenChanged in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WhenChanged")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> WhenChanged
        {
            get
            {
                return this._WhenChanged;
            }
            set
            {
                this.OnWhenChangedChanging(value);
                this._WhenChanged = value;
                this.OnWhenChangedChanged();
                this.OnPropertyChanged("WhenChanged");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _WhenChanged;
        partial void OnWhenChangedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnWhenChangedChanged();
        /// <summary>
        /// There are no comments for Property WhenCreated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WhenCreated")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> WhenCreated
        {
            get
            {
                return this._WhenCreated;
            }
            set
            {
                this.OnWhenCreatedChanging(value);
                this._WhenCreated = value;
                this.OnWhenCreatedChanged();
                this.OnPropertyChanged("WhenCreated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _WhenCreated;
        partial void OnWhenCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnWhenCreatedChanged();
        /// <summary>
        /// There are no comments for Property ExchangeObjectId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ExchangeObjectId")]
        public virtual global::System.Nullable<global::System.Guid> ExchangeObjectId
        {
            get
            {
                return this._ExchangeObjectId;
            }
            set
            {
                this.OnExchangeObjectIdChanging(value);
                this._ExchangeObjectId = value;
                this.OnExchangeObjectIdChanged();
                this.OnPropertyChanged("ExchangeObjectId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ExchangeObjectId;
        partial void OnExchangeObjectIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnExchangeObjectIdChanged();
        /// <summary>
        /// There are no comments for Property OrganizationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OrganizationId")]
        public virtual string OrganizationId
        {
            get
            {
                return this._OrganizationId;
            }
            set
            {
                this.OnOrganizationIdChanging(value);
                this._OrganizationId = value;
                this.OnOrganizationIdChanged();
                this.OnPropertyChanged("OrganizationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _OrganizationId;
        partial void OnOrganizationIdChanging(string value);
        partial void OnOrganizationIdChanged();
        /// <summary>
        /// There are no comments for Property Guid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Guid")]
        public virtual global::System.Nullable<global::System.Guid> Guid
        {
            get
            {
                return this._Guid;
            }
            set
            {
                this.OnGuidChanging(value);
                this._Guid = value;
                this.OnGuidChanged();
                this.OnPropertyChanged("Guid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _Guid;
        partial void OnGuidChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnGuidChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
