//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 3/25/2026 1:02:19 PM
namespace AdminApiClient.For.ExchangeOnline.OData
{
    /// <summary>
    /// There are no comments for UnifiedRbacRoleAssignmentSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("UnifiedRbacRoleAssignmentSingle")]
    public partial class UnifiedRbacRoleAssignmentSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<UnifiedRbacRoleAssignment>
    {
        /// <summary>
        /// Initialize a new UnifiedRbacRoleAssignmentSingle object.
        /// </summary>
        public UnifiedRbacRoleAssignmentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new UnifiedRbacRoleAssignmentSingle object.
        /// </summary>
        public UnifiedRbacRoleAssignmentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new UnifiedRbacRoleAssignmentSingle object.
        /// </summary>
        public UnifiedRbacRoleAssignmentSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<UnifiedRbacRoleAssignment> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for RoleDefinition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("roleDefinition")]
        public virtual global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacRoleDefinitionSingle RoleDefinition
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RoleDefinition == null))
                {
                    this._RoleDefinition = new global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacRoleDefinitionSingle(this.Context, GetPath("roleDefinition"));
                }
                return this._RoleDefinition;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacRoleDefinitionSingle _RoleDefinition;
        /// <summary>
        /// There are no comments for AppScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("appScope")]
        public virtual global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacManagementScopeSingle AppScope
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._AppScope == null))
                {
                    this._AppScope = new global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacManagementScopeSingle(this.Context, GetPath("appScope"));
                }
                return this._AppScope;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacManagementScopeSingle _AppScope;
    }
    /// <summary>
    /// There are no comments for UnifiedRbacRoleAssignment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.EntitySet("UnifiedRbacRoleAssignment")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("UnifiedRbacRoleAssignment")]
    public partial class UnifiedRbacRoleAssignment : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new UnifiedRbacRoleAssignment object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="roleDefinition">Initial value of RoleDefinition.</param>
        /// <param name="appScope">Initial value of AppScope.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static UnifiedRbacRoleAssignment CreateUnifiedRbacRoleAssignment(string ID, global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacRoleDefinition roleDefinition, global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacManagementScope appScope)
        {
            UnifiedRbacRoleAssignment unifiedRbacRoleAssignment = new UnifiedRbacRoleAssignment();
            unifiedRbacRoleAssignment.Id = ID;
            if ((roleDefinition == null))
            {
                throw new global::System.ArgumentNullException("roleDefinition");
            }
            unifiedRbacRoleAssignment.RoleDefinition = roleDefinition;
            if ((appScope == null))
            {
                throw new global::System.ArgumentNullException("appScope");
            }
            unifiedRbacRoleAssignment.AppScope = appScope;
            return unifiedRbacRoleAssignment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property PrincipalId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("principalId")]
        public virtual string PrincipalId
        {
            get
            {
                return this._PrincipalId;
            }
            set
            {
                this.OnPrincipalIdChanging(value);
                this._PrincipalId = value;
                this.OnPrincipalIdChanged();
                this.OnPropertyChanged("principalId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PrincipalId;
        partial void OnPrincipalIdChanging(string value);
        partial void OnPrincipalIdChanged();
        /// <summary>
        /// There are no comments for Property RoleDefinitionId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("roleDefinitionId")]
        public virtual string RoleDefinitionId
        {
            get
            {
                return this._RoleDefinitionId;
            }
            set
            {
                this.OnRoleDefinitionIdChanging(value);
                this._RoleDefinitionId = value;
                this.OnRoleDefinitionIdChanged();
                this.OnPropertyChanged("roleDefinitionId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RoleDefinitionId;
        partial void OnRoleDefinitionIdChanging(string value);
        partial void OnRoleDefinitionIdChanged();
        /// <summary>
        /// There are no comments for Property DirectoryScopeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("directoryScopeId")]
        public virtual string DirectoryScopeId
        {
            get
            {
                return this._DirectoryScopeId;
            }
            set
            {
                this.OnDirectoryScopeIdChanging(value);
                this._DirectoryScopeId = value;
                this.OnDirectoryScopeIdChanged();
                this.OnPropertyChanged("directoryScopeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DirectoryScopeId;
        partial void OnDirectoryScopeIdChanging(string value);
        partial void OnDirectoryScopeIdChanged();
        /// <summary>
        /// There are no comments for Property AppScopeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("appScopeId")]
        public virtual string AppScopeId
        {
            get
            {
                return this._AppScopeId;
            }
            set
            {
                this.OnAppScopeIdChanging(value);
                this._AppScopeId = value;
                this.OnAppScopeIdChanged();
                this.OnPropertyChanged("appScopeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AppScopeId;
        partial void OnAppScopeIdChanging(string value);
        partial void OnAppScopeIdChanged();
        /// <summary>
        /// There are no comments for Property Identity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("identity")]
        public virtual string Identity
        {
            get
            {
                return this._Identity;
            }
            set
            {
                this.OnIdentityChanging(value);
                this._Identity = value;
                this.OnIdentityChanged();
                this.OnPropertyChanged("identity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Identity;
        partial void OnIdentityChanging(string value);
        partial void OnIdentityChanged();
        /// <summary>
        /// There are no comments for Property User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("user")]
        public virtual string User
        {
            get
            {
                return this._User;
            }
            set
            {
                this.OnUserChanging(value);
                this._User = value;
                this.OnUserChanged();
                this.OnPropertyChanged("user");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _User;
        partial void OnUserChanging(string value);
        partial void OnUserChanged();
        /// <summary>
        /// There are no comments for Property AssignmentMethod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("assignmentMethod")]
        public virtual string AssignmentMethod
        {
            get
            {
                return this._AssignmentMethod;
            }
            set
            {
                this.OnAssignmentMethodChanging(value);
                this._AssignmentMethod = value;
                this.OnAssignmentMethodChanged();
                this.OnPropertyChanged("assignmentMethod");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AssignmentMethod;
        partial void OnAssignmentMethodChanging(string value);
        partial void OnAssignmentMethodChanged();
        /// <summary>
        /// There are no comments for Property RoleAssigneeType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("roleAssigneeType")]
        public virtual string RoleAssigneeType
        {
            get
            {
                return this._RoleAssigneeType;
            }
            set
            {
                this.OnRoleAssigneeTypeChanging(value);
                this._RoleAssigneeType = value;
                this.OnRoleAssigneeTypeChanged();
                this.OnPropertyChanged("roleAssigneeType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RoleAssigneeType;
        partial void OnRoleAssigneeTypeChanging(string value);
        partial void OnRoleAssigneeTypeChanged();
        /// <summary>
        /// There are no comments for Property RoleAssignmentDelegationType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("roleAssignmentDelegationType")]
        public virtual string RoleAssignmentDelegationType
        {
            get
            {
                return this._RoleAssignmentDelegationType;
            }
            set
            {
                this.OnRoleAssignmentDelegationTypeChanging(value);
                this._RoleAssignmentDelegationType = value;
                this.OnRoleAssignmentDelegationTypeChanged();
                this.OnPropertyChanged("roleAssignmentDelegationType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RoleAssignmentDelegationType;
        partial void OnRoleAssignmentDelegationTypeChanging(string value);
        partial void OnRoleAssignmentDelegationTypeChanged();
        /// <summary>
        /// There are no comments for Property CustomRecipientWriteScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("customRecipientWriteScope")]
        public virtual string CustomRecipientWriteScope
        {
            get
            {
                return this._CustomRecipientWriteScope;
            }
            set
            {
                this.OnCustomRecipientWriteScopeChanging(value);
                this._CustomRecipientWriteScope = value;
                this.OnCustomRecipientWriteScopeChanged();
                this.OnPropertyChanged("customRecipientWriteScope");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CustomRecipientWriteScope;
        partial void OnCustomRecipientWriteScopeChanging(string value);
        partial void OnCustomRecipientWriteScopeChanged();
        /// <summary>
        /// There are no comments for Property CustomConfigWriteScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("customConfigWriteScope")]
        public virtual string CustomConfigWriteScope
        {
            get
            {
                return this._CustomConfigWriteScope;
            }
            set
            {
                this.OnCustomConfigWriteScopeChanging(value);
                this._CustomConfigWriteScope = value;
                this.OnCustomConfigWriteScopeChanged();
                this.OnPropertyChanged("customConfigWriteScope");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CustomConfigWriteScope;
        partial void OnCustomConfigWriteScopeChanging(string value);
        partial void OnCustomConfigWriteScopeChanged();
        /// <summary>
        /// There are no comments for Property RecipientReadScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("recipientReadScope")]
        public virtual string RecipientReadScope
        {
            get
            {
                return this._RecipientReadScope;
            }
            set
            {
                this.OnRecipientReadScopeChanging(value);
                this._RecipientReadScope = value;
                this.OnRecipientReadScopeChanged();
                this.OnPropertyChanged("recipientReadScope");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RecipientReadScope;
        partial void OnRecipientReadScopeChanging(string value);
        partial void OnRecipientReadScopeChanged();
        /// <summary>
        /// There are no comments for Property ConfigReadScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("configReadScope")]
        public virtual string ConfigReadScope
        {
            get
            {
                return this._ConfigReadScope;
            }
            set
            {
                this.OnConfigReadScopeChanging(value);
                this._ConfigReadScope = value;
                this.OnConfigReadScopeChanged();
                this.OnPropertyChanged("configReadScope");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ConfigReadScope;
        partial void OnConfigReadScopeChanging(string value);
        partial void OnConfigReadScopeChanged();
        /// <summary>
        /// There are no comments for Property RecipientWriteScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("recipientWriteScope")]
        public virtual string RecipientWriteScope
        {
            get
            {
                return this._RecipientWriteScope;
            }
            set
            {
                this.OnRecipientWriteScopeChanging(value);
                this._RecipientWriteScope = value;
                this.OnRecipientWriteScopeChanged();
                this.OnPropertyChanged("recipientWriteScope");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RecipientWriteScope;
        partial void OnRecipientWriteScopeChanging(string value);
        partial void OnRecipientWriteScopeChanged();
        /// <summary>
        /// There are no comments for Property ConfigWriteScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("configWriteScope")]
        public virtual string ConfigWriteScope
        {
            get
            {
                return this._ConfigWriteScope;
            }
            set
            {
                this.OnConfigWriteScopeChanging(value);
                this._ConfigWriteScope = value;
                this.OnConfigWriteScopeChanged();
                this.OnPropertyChanged("configWriteScope");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ConfigWriteScope;
        partial void OnConfigWriteScopeChanging(string value);
        partial void OnConfigWriteScopeChanged();
        /// <summary>
        /// There are no comments for Property Enabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("enabled")]
        public virtual global::System.Nullable<bool> Enabled
        {
            get
            {
                return this._Enabled;
            }
            set
            {
                this.OnEnabledChanging(value);
                this._Enabled = value;
                this.OnEnabledChanged();
                this.OnPropertyChanged("enabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _Enabled;
        partial void OnEnabledChanging(global::System.Nullable<bool> value);
        partial void OnEnabledChanged();
        /// <summary>
        /// There are no comments for Property RoleAssigneeName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("roleAssigneeName")]
        public virtual string RoleAssigneeName
        {
            get
            {
                return this._RoleAssigneeName;
            }
            set
            {
                this.OnRoleAssigneeNameChanging(value);
                this._RoleAssigneeName = value;
                this.OnRoleAssigneeNameChanged();
                this.OnPropertyChanged("roleAssigneeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RoleAssigneeName;
        partial void OnRoleAssigneeNameChanging(string value);
        partial void OnRoleAssigneeNameChanged();
        /// <summary>
        /// There are no comments for Property IsValid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("isValid")]
        public virtual global::System.Nullable<bool> IsValid
        {
            get
            {
                return this._IsValid;
            }
            set
            {
                this.OnIsValidChanging(value);
                this._IsValid = value;
                this.OnIsValidChanged();
                this.OnPropertyChanged("isValid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _IsValid;
        partial void OnIsValidChanging(global::System.Nullable<bool> value);
        partial void OnIsValidChanged();
        /// <summary>
        /// There are no comments for Property DisplayName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("displayName")]
        public virtual string DisplayName
        {
            get
            {
                return this._DisplayName;
            }
            set
            {
                this.OnDisplayNameChanging(value);
                this._DisplayName = value;
                this.OnDisplayNameChanged();
                this.OnPropertyChanged("displayName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DisplayName;
        partial void OnDisplayNameChanging(string value);
        partial void OnDisplayNameChanged();
        /// <summary>
        /// There are no comments for Property DistinguishedName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("distinguishedName")]
        public virtual string DistinguishedName
        {
            get
            {
                return this._DistinguishedName;
            }
            set
            {
                this.OnDistinguishedNameChanging(value);
                this._DistinguishedName = value;
                this.OnDistinguishedNameChanged();
                this.OnPropertyChanged("distinguishedName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DistinguishedName;
        partial void OnDistinguishedNameChanging(string value);
        partial void OnDistinguishedNameChanged();
        /// <summary>
        /// There are no comments for Property Guid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("guid")]
        public virtual string Guid
        {
            get
            {
                return this._Guid;
            }
            set
            {
                this.OnGuidChanging(value);
                this._Guid = value;
                this.OnGuidChanged();
                this.OnPropertyChanged("guid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Guid;
        partial void OnGuidChanging(string value);
        partial void OnGuidChanged();
        /// <summary>
        /// There are no comments for Property RecipientAdministrativeUnitScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("recipientAdministrativeUnitScope")]
        public virtual string RecipientAdministrativeUnitScope
        {
            get
            {
                return this._RecipientAdministrativeUnitScope;
            }
            set
            {
                this.OnRecipientAdministrativeUnitScopeChanging(value);
                this._RecipientAdministrativeUnitScope = value;
                this.OnRecipientAdministrativeUnitScopeChanged();
                this.OnPropertyChanged("recipientAdministrativeUnitScope");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RecipientAdministrativeUnitScope;
        partial void OnRecipientAdministrativeUnitScopeChanging(string value);
        partial void OnRecipientAdministrativeUnitScopeChanged();
        /// <summary>
        /// There are no comments for Property RoleDefinition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("roleDefinition")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "RoleDefinition is required.")]
        public virtual global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacRoleDefinition RoleDefinition
        {
            get
            {
                return this._RoleDefinition;
            }
            set
            {
                this.OnRoleDefinitionChanging(value);
                this._RoleDefinition = value;
                this.OnRoleDefinitionChanged();
                this.OnPropertyChanged("roleDefinition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacRoleDefinition _RoleDefinition;
        partial void OnRoleDefinitionChanging(global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacRoleDefinition value);
        partial void OnRoleDefinitionChanged();
        /// <summary>
        /// There are no comments for Property AppScope in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("appScope")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AppScope is required.")]
        public virtual global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacManagementScope AppScope
        {
            get
            {
                return this._AppScope;
            }
            set
            {
                this.OnAppScopeChanging(value);
                this._AppScope = value;
                this.OnAppScopeChanged();
                this.OnPropertyChanged("appScope");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacManagementScope _AppScope;
        partial void OnAppScopeChanging(global::AdminApiClient.For.ExchangeOnline.OData.UnifiedRbacManagementScope value);
        partial void OnAppScopeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
